import type { Link } from '../domain/link'

// Lineage, oldest to newest. `Direct` means someone documented the hand-off
// (a citation, a creator’s own account, or the same people carrying the idea
// across). `Echo` means kinship or parallel rediscovery without one.

export const links: ReadonlyArray<Link> = [
  // FIELDS

  {
    from: 'field-logic',
    to: 'lambda-calculus',
    ideas: ['lambda', 'proofs'],
    note: 'Church built the λ-calculus as a foundation for logic, and in 1936 used it to show the Entscheidungsproblem has no solution.',
    kind: 'Direct',
  },
  {
    from: 'field-logic',
    to: 'turing-machine',
    ideas: ['proofs'],
    note: 'Turing invented his machines to answer Hilbert and Ackermann’s decision problem, reaching the same negative answer as Church.',
    kind: 'Direct',
  },
  {
    from: 'field-logic',
    to: 'field-proof',
    ideas: ['proofs'],
    note: 'Heyting’s 1930 formalisation of intuitionistic logic answered Hilbert’s demand for formal rigour on behalf of Brouwer’s constructive mathematics.',
    kind: 'Direct',
  },
  {
    from: 'field-logic',
    to: 'prolog',
    ideas: ['logic'],
    note: 'Prolog runs on J. Alan Robinson’s resolution principle (1965), a method for automated theorem proving in first-order logic.',
    kind: 'Direct',
  },
  {
    from: 'field-logic',
    to: 'lucid',
    ideas: ['frp'],
    note: 'Ashcroft and Wadge first presented Lucid as a formal logical system in which programs could be both written and proved correct.',
    kind: 'Direct',
  },
  {
    from: 'field-proof',
    to: 'curry-howard',
    ideas: ['proofs'],
    note: 'The Brouwer–Heyting–Kolmogorov reading, a proof of A → B as a method for transforming proofs, is the informal heart of Curry–Howard.',
    kind: 'Direct',
  },
  {
    from: 'field-proof',
    to: 'automath',
    ideas: ['proofs'],
    note: 'Automath encoded natural-deduction-style proofs as typed terms, so checking a proof became checking a type.',
    kind: 'Direct',
  },
  {
    from: 'field-proof',
    to: 'martin-lof',
    ideas: ['proofs'],
    note: 'Martin-Löf set out to give Brouwer’s constructive mathematics a precise foundation that can also be run as programs.',
    kind: 'Direct',
  },
  {
    from: 'field-proof',
    to: 'linear-logic',
    ideas: ['ownership'],
    note: 'Linear logic refines Gentzen’s sequent calculus by restricting the structural rules that let assumptions be copied or discarded.',
    kind: 'Direct',
  },
  {
    from: 'field-category',
    to: 'moggi',
    ideas: ['monads'],
    note: 'Moggi took monads, a construction from category theory, and used them to model computational effects.',
    kind: 'Direct',
  },
  {
    from: 'field-category',
    to: 'haskell',
    ideas: ['monads', 'typeclasses'],
    note: 'Haskell’s Functor and Monad classes take their names and laws straight from category theory.',
    kind: 'Direct',
  },
  {
    from: 'field-category',
    to: 'caml',
    ideas: ['lambda'],
    note: 'Caml is named for the Categorical Abstract Machine, an implementation model built from Curien’s categorical combinators.',
    kind: 'Direct',
  },
  {
    from: 'field-category',
    to: 'algebraic-effects',
    ideas: ['effects'],
    note: 'Plotkin and Power described effects using Lawvere theories, an algebraic tool from category theory, rather than starting from monads.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'ipl',
    ideas: ['logic'],
    note: 'Newell, Shaw and Simon built IPL to write the Logic Theorist, the heuristic theorem prover they brought to the 1956 Dartmouth workshop.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'lisp',
    ideas: ['homoiconicity'],
    note: 'McCarthy designed Lisp for AI programs, such as his proposed Advice Taker, that had to build and inspect symbolic expressions.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'planner',
    ideas: ['logic'],
    note: 'Planner was built for problem solving and robot planning at MIT’s AI Lab.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'prolog',
    ideas: ['logic'],
    note: 'Colmerauer built Prolog for natural-language understanding, a classic AI problem.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'macsyma',
    ideas: ['homoiconicity'],
    note: 'Symbolic integration began as an AI problem; Macsyma grew from programs like James Slagle’s SAINT and Joel Moses’s SIN.',
    kind: 'Direct',
  },
  {
    from: 'field-ai',
    to: 'alphaproof',
    ideas: ['proofs', 'logic'],
    note: 'The Logic Theorist proved theorems by heuristic search in 1956; AlphaProof does the same with a search policy learned by a neural network.',
    kind: 'Direct',
  },
  {
    from: 'field-notation',
    to: 'apl',
    ideas: ['arrays'],
    note: 'APL is Iverson’s blackboard notation for algorithms, made executable.',
    kind: 'Direct',
  },
  {
    from: 'field-notation',
    to: 'fortran',
    ideas: ['arrays'],
    note: 'Fortran’s name abbreviates Formula Translation: its promise was arithmetic written roughly as it appears on paper.',
    kind: 'Direct',
  },
  {
    from: 'field-notation',
    to: 'julia',
    ideas: ['arrays'],
    note: 'Julia accepts Unicode operators such as ∈, √ and ⊗, typed with LaTeX-style tab completion, so code can look like the paper it implements.',
    kind: 'Direct',
  },
  {
    from: 'field-concurrency',
    to: 'csp',
    ideas: ['actors'],
    note: 'Hoare built CSP on Dijkstra’s guarded commands, adding input and output between parallel processes.',
    kind: 'Direct',
  },
  {
    from: 'field-concurrency',
    to: 'pi-calculus',
    ideas: ['actors'],
    note: 'The π-calculus grew out of Milner’s CCS, adding the ability to send channel names as messages.',
    kind: 'Direct',
  },
  {
    from: 'field-concurrency',
    to: 'stm-paper',
    ideas: ['stm'],
    note: 'Herlihy, a co-author, had proposed transactional memory with Eliot Moss in 1993, borrowing the transaction from databases.',
    kind: 'Direct',
  },
  {
    from: 'field-education',
    to: 'logo',
    ideas: ['repl'],
    note: 'Logo was designed for children, putting into practice Papert’s view that people learn by building things.',
    kind: 'Direct',
  },
  {
    from: 'field-education',
    to: 'smalltalk',
    ideas: ['objects', 'repl'],
    note: 'Kay’s Dynabook, a personal computer for children, was the brief for Smalltalk, and early Smalltalk was tried out with children at PARC.',
    kind: 'Direct',
  },
  {
    from: 'field-education',
    to: 'racket',
    ideas: ['repl'],
    note: 'PLT Scheme grew out of Felleisen’s TeachScheme! project, with graded student languages and the beginner-friendly DrScheme editor.',
    kind: 'Direct',
  },
  {
    from: 'field-databases',
    to: 'sql',
    ideas: ['logic'],
    note: 'SEQUEL was designed to make Codd’s relational model usable by people who were not mathematicians.',
    kind: 'Direct',
  },
  {
    from: 'field-databases',
    to: 'datalog',
    ideas: ['logic'],
    note: 'Datalog came from treating a relational database as a set of logical facts and its queries as rules.',
    kind: 'Direct',
  },
  {
    from: 'field-control',
    to: 'esterel',
    ideas: ['frp'],
    note: 'Esterel was developed for control software, where each reaction to sensor inputs must finish before the next tick.',
    kind: 'Direct',
  },
  {
    from: 'field-control',
    to: 'lustre',
    ideas: ['frp'],
    note: 'Lustre programs mirror the block diagrams and sampled equations control engineers already used.',
    kind: 'Direct',
  },
  {
    from: 'field-telecom',
    to: 'erlang',
    ideas: ['actors', 'supervision'],
    note: 'Erlang was designed for telephone switching: massive concurrency, soft real-time deadlines, code upgrades without downtime and recovery from failure.',
    kind: 'Direct',
  },
  {
    from: 'field-telecom',
    to: 'otp',
    ideas: ['supervision'],
    note: 'OTP packaged the design patterns of Ericsson’s switching products, hence its name, the Open Telecom Platform.',
    kind: 'Direct',
  },
  {
    from: 'field-finance',
    to: 'visicalc',
    ideas: ['frp'],
    note: 'Bricklin conceived VisiCalc at Harvard Business School, watching a professor laboriously recompute a financial model on a blackboard.',
    kind: 'Direct',
  },
  {
    from: 'field-finance',
    to: 'k',
    ideas: ['arrays'],
    note: 'Whitney built A+ at Morgan Stanley in 1988, and K and kdb+ made tick-data analysis for trading firms their main market.',
    kind: 'Direct',
  },
  {
    from: 'field-finance',
    to: 'ocaml',
    ideas: ['adts'],
    note: 'Jane Street adopted OCaml in the mid-2000s and became one of the language’s biggest industrial contributors.',
    kind: 'Direct',
  },

  // FOUNDATIONS & THEORIES

  {
    from: 'combinatory-logic',
    to: 'lambda-calculus',
    ideas: ['lambda'],
    note: 'Schönfinkel’s combinators and Church’s λ-calculus turned out to express exactly the same functions, and each translates into the other.',
    kind: 'Echo',
  },
  {
    from: 'combinatory-logic',
    to: 'sasl',
    ideas: ['laziness'],
    note: 'Turner’s 1979 implementation compiled SASL programs into S, K and I combinators and evaluated them by graph reduction.',
    kind: 'Direct',
  },
  {
    from: 'combinatory-logic',
    to: 'hindley-milner',
    ideas: ['inference'],
    note: 'Hindley’s 1969 paper was titled “The principal type-scheme of an object in combinatory logic”.',
    kind: 'Direct',
  },
  {
    from: 'combinatory-logic',
    to: 'curry-howard',
    ideas: ['proofs'],
    note: 'Curry first noticed the correspondence in combinatory logic: the types of K and S match two axioms of implicational logic.',
    kind: 'Direct',
  },
  {
    from: 'combinatory-logic',
    to: 'j',
    ideas: ['pipelines'],
    note: 'J’s tacit trains are combinators in all but name: the hook (f g) y computes y f (g y), the S combinator in disguise.',
    kind: 'Echo',
  },
  {
    from: 'lambda-calculus',
    to: 'typed-lambda',
    ideas: ['lambda', 'proofs'],
    note: 'Church added simple types to his own calculus in 1940 to rule out the paradoxes of the untyped version.',
    kind: 'Direct',
  },
  {
    from: 'lambda-calculus',
    to: 'lisp',
    ideas: ['lambda'],
    note: 'McCarthy borrowed Church’s λ notation for anonymous functions; by his own account he did not read far enough into Church to adopt the rest.',
    kind: 'Direct',
  },
  {
    from: 'lambda-calculus',
    to: 'iswim',
    ideas: ['lambda'],
    note: 'Landin explained ALGOL 60 by translating it into λ-calculus, and ISWIM was λ-calculus with syntactic sugar.',
    kind: 'Direct',
  },
  {
    from: 'lambda-calculus',
    to: 'scheme',
    ideas: ['lambda'],
    note: 'Scheme’s first report called it an interpreter for extended lambda calculus, and lambda is its one way to make a function.',
    kind: 'Direct',
  },
  {
    from: 'lambda-calculus',
    to: 'haskell',
    ideas: ['lambda'],
    note: 'Haskell writes λx. e as \\x -> e, the backslash chosen because it looks a little like a λ.',
    kind: 'Direct',
  },
  {
    from: 'lambda-calculus',
    to: 'call-by-need',
    ideas: ['laziness'],
    note: 'Wadsworth found call-by-need while studying how to reduce λ-terms efficiently by sharing subterms in a graph.',
    kind: 'Direct',
  },
  {
    from: 'typed-lambda',
    to: 'hindley-milner',
    ideas: ['inference'],
    note: 'Hindley–Milner inference reconstructs simple types, plus let-polymorphism, for terms written with no annotations at all.',
    kind: 'Direct',
  },
  {
    from: 'typed-lambda',
    to: 'system-f',
    ideas: ['proofs'],
    note: 'System F extends the simply typed λ-calculus with abstraction over types.',
    kind: 'Direct',
  },
  {
    from: 'typed-lambda',
    to: 'curry-howard',
    ideas: ['proofs'],
    note: 'Howard’s correspondence pairs simply typed λ-terms with natural-deduction proofs in intuitionistic logic.',
    kind: 'Direct',
  },
  {
    from: 'typed-lambda',
    to: 'lcf',
    ideas: ['proofs'],
    note: 'LCF implemented Dana Scott’s logic of computable functions, which reasons about a typed λ-calculus.',
    kind: 'Direct',
  },
  {
    from: 'hindley-milner',
    to: 'ml',
    ideas: ['inference'],
    note: 'Milner’s algorithm W gave ML complete type inference.',
    kind: 'Direct',
  },
  {
    from: 'hindley-milner',
    to: 'miranda',
    ideas: ['inference'],
    note: 'Miranda used Hindley–Milner polymorphic types, so lazy programs needed no type annotations.',
    kind: 'Direct',
  },
  {
    from: 'hindley-milner',
    to: 'haskell',
    ideas: ['inference'],
    note: 'Haskell’s type system is Hindley–Milner extended with type classes.',
    kind: 'Direct',
  },
  {
    from: 'hindley-milner',
    to: 'typeclasses-paper',
    ideas: ['typeclasses', 'inference'],
    note: 'Wadler and Blott designed type classes as an extension of Hindley–Milner, inferring the needed instances along with the types.',
    kind: 'Direct',
  },
  {
    from: 'curry-howard',
    to: 'martin-lof',
    ideas: ['proofs'],
    note: 'Martin-Löf made propositions-as-types the founding principle of his type theory.',
    kind: 'Direct',
  },
  {
    from: 'curry-howard',
    to: 'coq',
    ideas: ['proofs'],
    note: 'In Coq a theorem is a type and its proof is a term; the Calculus of Constructions is Curry–Howard for higher-order logic.',
    kind: 'Direct',
  },
  {
    from: 'curry-howard',
    to: 'agda',
    ideas: ['proofs'],
    note: 'Agda has no separate proof language: proofs are ordinary programs whose types are propositions.',
    kind: 'Direct',
  },
  {
    from: 'curry-howard',
    to: 'lean',
    ideas: ['proofs'],
    note: 'Lean’s kernel checks a proof by type-checking a term, exactly as Curry–Howard prescribes.',
    kind: 'Direct',
  },
  {
    from: 'system-f',
    to: 'haskell',
    ideas: ['inference'],
    note: 'GHC compiles Haskell to Core, a variant of System F extended with type-equality coercions (System FC).',
    kind: 'Direct',
  },
  {
    from: 'martin-lof',
    to: 'agda',
    ideas: ['proofs'],
    note: 'Agda implements a version of Martin-Löf type theory, with dependent pattern matching.',
    kind: 'Direct',
  },
  {
    from: 'martin-lof',
    to: 'idris',
    ideas: ['proofs'],
    note: 'Idris inherits dependent function types from this line, so a type like Vect n a can mention the value n.',
    kind: 'Direct',
  },
  {
    from: 'call-by-need',
    to: 'sasl',
    ideas: ['laziness'],
    note: 'SASL adopted lazy evaluation in 1976, the year the Henderson–Morris and Friedman–Wise lazy evaluators were published.',
    kind: 'Direct',
  },
  {
    from: 'call-by-need',
    to: 'haskell',
    ideas: ['laziness'],
    note: 'Haskell made call-by-need its default; GHC overwrites each evaluated thunk with its value so it is computed only once.',
    kind: 'Direct',
  },
  {
    from: 'call-by-need',
    to: 'okasaki',
    ideas: ['laziness'],
    note: 'Okasaki used lazy evaluation to get good amortised bounds for purely functional queues and deques.',
    kind: 'Direct',
  },
  {
    from: 'actor-model',
    to: 'scheme',
    ideas: ['actors', 'lambda'],
    note: 'Sussman and Steele built Scheme to understand actors, and found that in their interpreter actors and closures were the same thing.',
    kind: 'Direct',
  },
  {
    from: 'actor-model',
    to: 'erlang',
    ideas: ['actors'],
    note: 'Erlang processes behave like actors, but Armstrong said Ericsson’s team arrived at the design without knowing Hewitt’s work.',
    kind: 'Echo',
  },
  {
    from: 'actor-model',
    to: 'akka',
    ideas: ['actors'],
    note: 'Akka presents itself as an implementation of the actor model for the JVM.',
    kind: 'Direct',
  },
  {
    from: 'actor-model',
    to: 'swift',
    ideas: ['actors'],
    note: 'Swift 5.5 (2021) added actor types, following a concurrency design Lattner had sketched in 2017 around the actor model.',
    kind: 'Direct',
  },
  {
    from: 'csp',
    to: 'go',
    ideas: ['fibers', 'actors'],
    note: 'Go’s FAQ credits Hoare’s CSP for goroutines and channels, by way of Newsqueak and Limbo.',
    kind: 'Direct',
  },
  {
    from: 'csp',
    to: 'cml',
    ideas: ['fibers'],
    note: 'Concurrent ML started from CSP-style synchronous channels and made each possible communication a first-class event.',
    kind: 'Direct',
  },
  {
    from: 'csp',
    to: 'clojure',
    ideas: ['fibers'],
    note: 'Clojure’s core.async library (2013) brought CSP-style channels and go blocks to Clojure and ClojureScript.',
    kind: 'Direct',
  },
  {
    from: 'csp',
    to: 'rust',
    ideas: ['fibers'],
    note: 'The Rust Reference credits its channels to Newsqueak, Alef and Limbo, Bell Labs languages in the CSP line.',
    kind: 'Direct',
  },
  {
    from: 'linear-logic',
    to: 'rust',
    ideas: ['ownership'],
    note: 'Rust’s moves are affine types, a relative of linear logic that permits discarding a value but not copying it.',
    kind: 'Echo',
  },
  {
    from: 'linear-logic',
    to: 'haskell',
    ideas: ['ownership'],
    note: 'GHC 9.0 (2021) added linear function types, based on the 2018 Linear Haskell paper and ultimately on Girard’s logic.',
    kind: 'Direct',
  },
  {
    from: 'moggi',
    to: 'haskell',
    ideas: ['monads'],
    note: 'Through Wadler’s papers, Moggi’s monads became Haskell’s answer to I/O, adopted in Haskell 1.3 (1996).',
    kind: 'Direct',
  },
  {
    from: 'moggi',
    to: 'algebraic-effects',
    ideas: ['effects', 'monads'],
    note: 'Plotkin and Power set out to explain where Moggi’s monads come from, generating them from effect operations and equations.',
    kind: 'Direct',
  },
  {
    from: 'typeclasses-paper',
    to: 'haskell',
    ideas: ['typeclasses'],
    note: 'Type classes went into the first Haskell report, to overload equality and arithmetic.',
    kind: 'Direct',
  },
  {
    from: 'typeclasses-paper',
    to: 'scala',
    ideas: ['typeclasses'],
    note: 'Oliveira, Moors and Odersky’s 2010 paper “Type Classes as Objects and Implicits” showed how Scala encodes type classes; Scala 3 calls the instances givens.',
    kind: 'Direct',
  },
  {
    from: 'typeclasses-paper',
    to: 'lean',
    ideas: ['typeclasses'],
    note: 'Lean’s instances descend from type classes, resolved by a tabled algorithm (2020) built to cope with Mathlib’s huge class hierarchy.',
    kind: 'Direct',
  },
  {
    from: 'fran',
    to: 'elm',
    ideas: ['frp'],
    note: 'Czaplicki’s thesis cast Elm as functional reactive programming for GUIs, in the line that Fran began.',
    kind: 'Direct',
  },
  {
    from: 'fran',
    to: 'signals',
    ideas: ['frp'],
    note: 'A signal is a time-varying value, the core idea of a Fran behaviour, sampled whenever something reads it.',
    kind: 'Echo',
  },
  {
    from: 'okasaki',
    to: 'clojure',
    ideas: ['immutability'],
    note: 'Hickey built Clojure’s persistent maps and vectors on Bagwell’s hash array mapped tries.',
    kind: 'Direct',
  },
  {
    from: 'okasaki',
    to: 'scala',
    ideas: ['immutability'],
    note: 'Phil Bagwell worked at EPFL, and Scala’s immutable HashMap and Vector are based on his tries.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'eff',
    ideas: ['effects'],
    note: 'Eff was designed by Pretnar, co-author of effect handlers, and Bauer to make handlers the main control structure of a language.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'koka',
    ideas: ['effects'],
    note: 'Koka types and handles algebraic effects, tracking which operations a function may perform as a row in its type.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'ocaml5',
    ideas: ['effects'],
    note: 'OCaml 5’s effect handlers come straight from Plotkin and Pretnar’s handlers, implemented with lightweight stack switching.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'unison',
    ideas: ['effects'],
    note: 'Unison’s abilities are algebraic effects with handlers, tracked in function types.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'react-hooks',
    ideas: ['effects'],
    note: 'The 2018 Hooks RFC lists algebraic effects in Multicore OCaml among the ideas hooks synthesise, and Abramov’s 2019 essay calls them the team’s mental model.',
    kind: 'Direct',
  },
  {
    from: 'algebraic-effects',
    to: 'effect',
    ideas: ['effects'],
    note: 'Effect’s R channel lets code ask for a service by type and have a Layer supply it further out, handler-like, though Effect itself is built on monads.',
    kind: 'Echo',
  },
  {
    from: 'stm-paper',
    to: 'zio',
    ideas: ['stm'],
    note: 'ZIO’s STM brings Haskell’s composable transactions, with retry and orElse, to Scala.',
    kind: 'Direct',
  },
  {
    from: 'stm-paper',
    to: 'clojure',
    ideas: ['stm'],
    note: 'Clojure shipped transactional refs the same era, built on multiversion concurrency control rather than Haskell’s design.',
    kind: 'Echo',
  },
  {
    from: 'sicp',
    to: 'racket',
    ideas: ['lambda'],
    note: 'Felleisen’s How to Design Programs was written in response to SICP, keeping Scheme but teaching beginners systematic design.',
    kind: 'Direct',
  },
  {
    from: 'mapreduce',
    to: 'spark',
    ideas: ['hof', 'immutability'],
    note: 'Spark kept MapReduce’s functional model but held immutable datasets in memory between steps, making iterative jobs far faster.',
    kind: 'Direct',
  },
  {
    from: 'backus-fp',
    to: 'j',
    ideas: ['pipelines'],
    note: 'J’s tacit programming shares FP’s function-level style: programs built by combining functions, never naming the data.',
    kind: 'Echo',
  },

  // LISP & SCHEME

  {
    from: 'ipl',
    to: 'lisp',
    ideas: ['homoiconicity'],
    note: 'McCarthy took linked lists from IPL but wanted them in a language with recursion and conditional expressions instead of assembly-like instructions.',
    kind: 'Direct',
  },
  {
    from: 'fortran',
    to: 'lisp',
    ideas: ['homoiconicity'],
    note: 'McCarthy’s first list-processing experiments used FLPL, a Fortran extension built at IBM; Fortran’s lack of recursion pushed him toward a new language.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'algol',
    ideas: ['lambda'],
    note: 'McCarthy, a member of the ALGOL 60 committee, brought conditional expressions from his Lisp work and argued for recursive procedures.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'smalltalk',
    ideas: ['repl', 'gc'],
    note: 'Kay credits the half-page definition of eval in the Lisp 1.5 manual; Smalltalk also took Lisp’s garbage collection and live, reflective environment.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'logo',
    ideas: ['repl', 'lambda'],
    note: 'Logo was designed as a dialect of Lisp, keeping its lists, recursion and interactive evaluation.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'maclisp',
    ideas: ['homoiconicity'],
    note: 'MacLisp descends from Lisp 1.5 by way of the PDP-1 Lisp written at MIT.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'python',
    ideas: ['lambda', 'hof'],
    note: 'lambda, map, filter and reduce arrived in Python 1.0 (1994) as a patch from a programmer who missed them from Lisp.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'ruby',
    ideas: ['hof', 'lambda'],
    note: 'Matz has described Ruby as starting from a simple Lisp, with blocks inspired by higher-order functions.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'clojure',
    ideas: ['homoiconicity', 'repl'],
    note: 'Clojure is a Lisp: code is data, macros transform it, and you develop at a REPL attached to the running program.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'mapreduce',
    ideas: ['hof'],
    note: 'The MapReduce paper says its abstraction was inspired by the map and reduce primitives of Lisp and other functional languages.',
    kind: 'Direct',
  },
  {
    from: 'lisp',
    to: 'elixir',
    ideas: ['homoiconicity'],
    note: 'Elixir’s quote and unquote follow Lisp’s macro tradition, with code represented as nested tuples instead of lists.',
    kind: 'Direct',
  },
  {
    from: 'maclisp',
    to: 'scheme',
    ideas: ['lambda'],
    note: 'The first Scheme interpreter was written in MacLisp, and Scheme kept its Lisp syntax and data.',
    kind: 'Direct',
  },
  {
    from: 'maclisp',
    to: 'common-lisp',
    ideas: ['homoiconicity'],
    note: 'Common Lisp was designed to unify MacLisp’s successors, among them Lisp Machine Lisp, NIL and Spice Lisp.',
    kind: 'Direct',
  },
  {
    from: 'maclisp',
    to: 'emacs-lisp',
    ideas: ['repl'],
    note: 'Stallman modelled Emacs Lisp mainly on MacLisp.',
    kind: 'Direct',
  },
  {
    from: 'maclisp',
    to: 'macsyma',
    ideas: ['homoiconicity'],
    note: 'Macsyma was written in MacLisp and was one of its most demanding users.',
    kind: 'Direct',
  },
  {
    from: 'maclisp',
    to: 'lisp-machines',
    ideas: ['repl'],
    note: 'Lisp Machine Lisp, later called Zetalisp, began as a descendant of MacLisp.',
    kind: 'Direct',
  },
  {
    from: 'logo',
    to: 'smalltalk',
    ideas: ['objects', 'repl'],
    note: 'Seeing children program in Logo convinced Kay that a personal computer should be programmable by children, the goal Smalltalk was built for.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'javascript',
    ideas: ['lambda'],
    note: 'Eich was recruited to put Scheme in the browser; JavaScript kept Scheme-style first-class functions under Java-like syntax, and they became full closures in JavaScript 1.2 (1997).',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'racket',
    ideas: ['lambda', 'homoiconicity'],
    note: 'Racket began as PLT Scheme and grew Scheme’s hygienic macros into a system for defining whole languages.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'sicp',
    ideas: ['lambda'],
    note: 'SICP teaches in Scheme, and Sussman, Scheme’s co-creator, is one of its authors.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'common-lisp',
    ideas: ['lambda'],
    note: 'Common Lisp adopted Scheme’s lexical scoping as its default, replacing MacLisp’s dynamic scope.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'minikanren',
    ideas: ['logic'],
    note: 'miniKanren was written as an embedding in Scheme, and its reference implementations still are.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'rust',
    ideas: ['homoiconicity'],
    note: 'The Rust Reference credits Scheme for hygienic macros; macro_rules! follows Scheme’s macro-by-example style.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'java',
    ideas: ['gc', 'lambda'],
    note: 'Guy Steele, Scheme’s co-creator, co-wrote the Java Language Specification, and later said Java had dragged C++ programmers about halfway to Lisp.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'julia',
    ideas: ['homoiconicity'],
    note: 'Julia’s founders asked for Lisp-style macros, and its front end was written in femtolisp, a small Scheme by Jeff Bezanson.',
    kind: 'Direct',
  },
  {
    from: 'scheme',
    to: 'ocaml5',
    ideas: ['continuations'],
    note: 'OCaml 5’s effect handlers capture delimited continuations, a structured form of the first-class continuations Scheme made famous with call/cc.',
    kind: 'Echo',
  },
  {
    from: 'lisp-machines',
    to: 'flavors',
    ideas: ['objects'],
    note: 'Flavors was written for the MIT Lisp Machine, whose window system was one of its first large applications.',
    kind: 'Direct',
  },
  {
    from: 'common-lisp',
    to: 'clos',
    ideas: ['dispatch'],
    note: 'CLOS was designed as Common Lisp’s object system and became part of the ANSI standard.',
    kind: 'Direct',
  },
  {
    from: 'common-lisp',
    to: 'algebraic-effects',
    ideas: ['effects'],
    note: 'Common Lisp’s restarts let a handler resume a failing computation, a decades-early relative of handlers that resume a continuation.',
    kind: 'Echo',
  },
  {
    from: 'common-lisp',
    to: 'clojure',
    ideas: ['homoiconicity'],
    note: 'Hickey worked in Common Lisp before Clojure, and Clojure’s defmacro and syntax-quote follow Common Lisp’s defmacro and backquote.',
    kind: 'Direct',
  },
  {
    from: 'clos',
    to: 'dylan',
    ideas: ['dispatch'],
    note: 'Dylan set out to keep CLOS’s generic functions and multiple dispatch in a smaller language that compiles well.',
    kind: 'Direct',
  },
  {
    from: 'clos',
    to: 'aspectj',
    ideas: ['dispatch'],
    note: 'Kiczales carried CLOS’s method combination and metaobject-protocol thinking into aspect-oriented programming.',
    kind: 'Direct',
  },
  {
    from: 'clos',
    to: 'julia',
    ideas: ['dispatch'],
    note: 'Julia chooses methods by the types of all arguments, the generic-function model CLOS made standard.',
    kind: 'Echo',
  },
  {
    from: 'racket',
    to: 'typed-racket',
    ideas: ['inference'],
    note: 'Typed Racket is itself a Racket language, built with its macro system to type existing Racket code module by module.',
    kind: 'Direct',
  },
  {
    from: 'typed-racket',
    to: 'typescript',
    ideas: ['inference'],
    note: 'TypeScript’s control-flow narrowing after typeof checks does what Typed Racket’s occurrence typing does after (number? x).',
    kind: 'Echo',
  },
  {
    from: 'minikanren',
    to: 'clojure',
    ideas: ['logic'],
    note: 'Clojure’s core.logic, by David Nolen, is a port of miniKanren.',
    kind: 'Direct',
  },
  {
    from: 'clojure',
    to: 'immutable-js',
    ideas: ['immutability'],
    note: 'Immutable.js’s README credits Clojure, with Scala, for popularising the tries it is built on.',
    kind: 'Direct',
  },
  {
    from: 'clojure',
    to: 'datomic',
    ideas: ['immutability'],
    note: 'Hickey brought Clojure’s values-not-places philosophy to the database, with queries written as Clojure data.',
    kind: 'Direct',
  },
  {
    from: 'clojure',
    to: 'mori',
    ideas: ['immutability'],
    note: 'Mori is ClojureScript’s persistent data structures, compiled and wrapped in a JavaScript API.',
    kind: 'Direct',
  },

  // OBJECTS & MESSAGES

  {
    from: 'simula',
    to: 'smalltalk',
    ideas: ['objects'],
    note: 'Kay credits Simula’s classes and objects, which he studied in 1966, as a seed of Smalltalk.',
    kind: 'Direct',
  },
  {
    from: 'simula',
    to: 'cpp',
    ideas: ['objects'],
    note: 'Stroustrup designed C with Classes to bring Simula’s classes to C.',
    kind: 'Direct',
  },
  {
    from: 'smalltalk',
    to: 'flavors',
    ideas: ['objects'],
    note: 'Cannon’s Flavors was inspired by Smalltalk’s objects and message passing.',
    kind: 'Direct',
  },
  {
    from: 'smalltalk',
    to: 'self',
    ideas: ['objects'],
    note: 'Self began as a dialect of Smalltalk, keeping its message passing and dropping classes.',
    kind: 'Direct',
  },
  {
    from: 'smalltalk',
    to: 'ruby',
    ideas: ['objects', 'lambda'],
    note: 'Ruby took Smalltalk’s everything-is-an-object model and its blocks.',
    kind: 'Direct',
  },
  {
    from: 'smalltalk',
    to: 'actor-model',
    ideas: ['actors'],
    note: 'Hewitt cited Smalltalk-72’s message passing among the influences on actors.',
    kind: 'Direct',
  },
  {
    from: 'flavors',
    to: 'clos',
    ideas: ['objects', 'dispatch'],
    note: 'CLOS took multiple inheritance, mixins and :before/:after method combination from Flavors, via New Flavors and Xerox’s CommonLoops.',
    kind: 'Direct',
  },
  {
    from: 'self',
    to: 'javascript',
    ideas: ['objects'],
    note: 'Eich took prototype-based inheritance, objects delegating to other objects, from Self.',
    kind: 'Direct',
  },
  {
    from: 'self',
    to: 'java',
    ideas: ['objects'],
    note: 'Java’s HotSpot VM came from Animorphic’s Strongtalk VM, built by Self veterans, carrying Self’s adaptive optimisation into Java.',
    kind: 'Direct',
  },
  {
    from: 'python',
    to: 'javascript',
    ideas: ['continuations'],
    note: 'Generators came to Mozilla’s JavaScript 1.7 (2006) modelled on Python’s, and were standardised in ES2015.',
    kind: 'Direct',
  },
  {
    from: 'python',
    to: 'numpy',
    ideas: ['arrays'],
    note: 'NumPy, and Numeric before it, made Python the host language for array programming.',
    kind: 'Direct',
  },
  {
    from: 'python',
    to: 'jax',
    ideas: ['arrays'],
    note: 'JAX transforms ordinary Python functions by tracing them as they run.',
    kind: 'Direct',
  },
  {
    from: 'dylan',
    to: 'julia',
    ideas: ['dispatch'],
    note: 'Bezanson’s thesis describes Julia’s rule for picking the most specific method as essentially Dylan’s, generalised to tuple types.',
    kind: 'Direct',
  },
  {
    from: 'javascript',
    to: 'typescript',
    ideas: ['lambda'],
    note: 'TypeScript is a typed superset of JavaScript and compiles to plain JavaScript, closures and all.',
    kind: 'Direct',
  },
  {
    from: 'javascript',
    to: 'react',
    ideas: ['lambda'],
    note: 'React components are plain JavaScript functions, and JSX compiles to ordinary function calls.',
    kind: 'Direct',
  },
  {
    from: 'javascript',
    to: 'underscore',
    ideas: ['hof'],
    note: 'Underscore filled the gap until ES5’s Array#map, filter and reduce were everywhere, delegating to the native versions where browsers had them.',
    kind: 'Direct',
  },
  {
    from: 'ruby',
    to: 'elixir',
    ideas: ['lambda'],
    note: 'Valim, a Rails core team member, gave Elixir do…end blocks, Ruby-like syntax and Ruby’s care for tooling and developer happiness.',
    kind: 'Direct',
  },
  {
    from: 'ruby',
    to: 'rust',
    ideas: ['lambda'],
    note: 'The Rust Reference credits Ruby for Rust’s closure syntax: |x| x + 1.',
    kind: 'Direct',
  },
  {
    from: 'ruby',
    to: 'underscore',
    ideas: ['hof'],
    note: 'Underscore’s aliases collect, select, detect and inject are the names of Ruby’s Enumerable methods, which Ruby got from Smalltalk.',
    kind: 'Echo',
  },
  {
    from: 'java',
    to: 'scala',
    ideas: ['objects'],
    note: 'Scala compiles to JVM bytecode and calls Java libraries directly.',
    kind: 'Direct',
  },
  {
    from: 'java',
    to: 'kotlin',
    ideas: ['objects'],
    note: 'JetBrains built Kotlin as a better language for its own Java codebase, fully interoperable with Java.',
    kind: 'Direct',
  },
  {
    from: 'java',
    to: 'csharp',
    ideas: ['gc', 'objects'],
    note: 'C# followed Java’s model of a garbage-collected class-based language on a virtual machine, after Microsoft’s legal dispute with Sun over Java.',
    kind: 'Direct',
  },
  {
    from: 'java',
    to: 'javascript',
    ideas: ['objects'],
    note: 'Netscape wanted Java-like syntax, and the name came from a marketing agreement with Sun.',
    kind: 'Direct',
  },
  {
    from: 'java',
    to: 'clojure',
    ideas: ['gc'],
    note: 'Clojure is hosted on the JVM, using its garbage collector, JIT compiler and libraries.',
    kind: 'Direct',
  },
  {
    from: 'pizza',
    to: 'scala',
    ideas: ['adts', 'lambda'],
    note: 'Odersky built Scala after Pizza and GJ, taking their first-class functions and algebraic types much further.',
    kind: 'Direct',
  },
  {
    from: 'csharp',
    to: 'linq',
    ideas: ['hof'],
    note: 'LINQ shipped in C# 3.0, which added lambdas, extension methods and local type inference to support it.',
    kind: 'Direct',
  },
  {
    from: 'csharp',
    to: 'typescript',
    ideas: ['objects'],
    note: 'Hejlsberg led both languages, and TypeScript’s classes, generics and enums look much like C#’s.',
    kind: 'Direct',
  },
  {
    from: 'csharp',
    to: 'fsharp',
    ideas: ['objects'],
    note: 'F# runs on .NET, where the runtime generics Syme had co-designed made a typed functional language practical.',
    kind: 'Direct',
  },
  {
    from: 'csharp',
    to: 'kotlin',
    ideas: ['typeclasses'],
    note: 'Breslav’s talk “Shoulders of Giants: Languages Kotlin Learned From” credits C# for extension functions, which add behaviour to an existing type.',
    kind: 'Direct',
  },
  {
    from: 'csharp',
    to: 'async-await',
    ideas: ['continuations'],
    note: 'async/await shipped in C# 5, with the compiler turning each async method into a state machine.',
    kind: 'Direct',
  },
  {
    from: 'linq',
    to: 'rx',
    ideas: ['frp', 'hof'],
    note: 'Meijer’s team built Rx as the push-based dual of LINQ, so LINQ’s operators work on event streams.',
    kind: 'Direct',
  },
  {
    from: 'typescript',
    to: 'effect',
    ideas: ['optionresult'],
    note: 'Effect leans on TypeScript’s inference and union types so errors and requirements are tracked without annotations.',
    kind: 'Direct',
  },
  {
    from: 'typescript',
    to: 'fp-ts',
    ideas: ['typeclasses'],
    note: 'fp-ts simulates higher-kinded types with TypeScript’s interface merging, registering each type constructor under a string key.',
    kind: 'Direct',
  },

  // IMPERATIVE & SYSTEMS

  {
    from: 'fortran',
    to: 'backus-fp',
    ideas: ['hof'],
    note: 'Backus had led the Fortran team; FP was his critique of the word-at-a-time style Fortran had made standard.',
    kind: 'Direct',
  },
  {
    from: 'fortran',
    to: 'matlab',
    ideas: ['arrays'],
    note: 'Moler’s original MATLAB was a Fortran program giving interactive access to the Fortran libraries LINPACK and EISPACK.',
    kind: 'Direct',
  },
  {
    from: 'algol',
    to: 'simula',
    ideas: ['objects'],
    note: 'Simula 67 extended ALGOL 60, adding classes to its block structure.',
    kind: 'Direct',
  },
  {
    from: 'algol',
    to: 'c',
    ideas: ['lambda'],
    note: 'C inherits ALGOL’s block structure and lexical scope by way of CPL, BCPL and B.',
    kind: 'Direct',
  },
  {
    from: 'algol',
    to: 'scheme',
    ideas: ['lambda'],
    note: 'Scheme took lexical scope and block structure from ALGOL, which is what makes its closures behave predictably.',
    kind: 'Direct',
  },
  {
    from: 'algol',
    to: 'iswim',
    ideas: ['lambda'],
    note: 'Landin’s ISWIM grew from his analysis of ALGOL 60 in terms of λ-calculus.',
    kind: 'Direct',
  },
  {
    from: 'algol',
    to: 'call-by-need',
    ideas: ['laziness'],
    note: 'ALGOL 60’s call-by-name delays an argument until it is used but re-evaluates it every time; call-by-need adds the memo.',
    kind: 'Echo',
  },
  {
    from: 'c',
    to: 'cyclone',
    ideas: ['ownership'],
    note: 'Cyclone kept C’s syntax and manual control of memory, adding regions to make them safe.',
    kind: 'Direct',
  },
  {
    from: 'cpp',
    to: 'java',
    ideas: ['objects'],
    note: 'Java took its class syntax from C++ while dropping multiple inheritance, operator overloading and manual memory management.',
    kind: 'Direct',
  },
  {
    from: 'cpp',
    to: 'rust',
    ideas: ['ownership'],
    note: 'The Rust Reference credits C++ for RAII, smart pointers, references and move semantics.',
    kind: 'Direct',
  },
  {
    from: 'cyclone',
    to: 'rust',
    ideas: ['ownership'],
    note: 'The Rust Reference lists Cyclone’s region-based memory management as an influence, the ancestor of Rust’s lifetimes.',
    kind: 'Direct',
  },
  {
    from: 'go',
    to: 'bubbletea',
    ideas: ['fibers'],
    note: 'Bubble Tea runs commands in goroutines and feeds their results back to Update as messages.',
    kind: 'Direct',
  },
  {
    from: 'rust',
    to: 'swift',
    ideas: ['ownership'],
    note: 'Lattner named Rust among Swift’s influences, and Swift 5.9 (2023) added noncopyable types with Rust-like ownership.',
    kind: 'Direct',
  },
  {
    from: 'rust',
    to: 'gleam',
    ideas: ['optionresult'],
    note: 'Gleam’s compiler is written in Rust, and its Result-based error handling will feel familiar to Rust programmers.',
    kind: 'Direct',
  },
  {
    from: 'swift',
    to: 'swiftui',
    ideas: ['frp'],
    note: 'SwiftUI depends on Swift 5.1’s property wrappers, such as @State, and function builders for its nested view syntax.',
    kind: 'Direct',
  },

  // THE ML FAMILY

  {
    from: 'iswim',
    to: 'ml',
    ideas: ['lambda'],
    note: 'ML followed ISWIM’s plan of λ-calculus with let-bindings and syntactic sugar, and added a type system.',
    kind: 'Direct',
  },
  {
    from: 'iswim',
    to: 'sasl',
    ideas: ['lambda'],
    note: 'Turner built SASL as a purely applicative subset of ISWIM.',
    kind: 'Direct',
  },
  {
    from: 'iswim',
    to: 'haskell',
    ideas: ['lambda'],
    note: 'Haskell’s indentation-sensitive layout descends from Landin’s off-side rule, and its where clauses from ISWIM.',
    kind: 'Direct',
  },
  {
    from: 'lcf',
    to: 'ml',
    ideas: ['inference', 'proofs'],
    note: 'ML was created as the metalanguage of Edinburgh LCF, the language for writing proof tactics.',
    kind: 'Direct',
  },
  {
    from: 'lcf',
    to: 'isabelle',
    ideas: ['proofs'],
    note: 'Paulson worked on Cambridge LCF before building Isabelle in the same style, with theorems as an abstract type.',
    kind: 'Direct',
  },
  {
    from: 'ml',
    to: 'sml',
    ideas: ['inference'],
    note: 'Standard ML standardised Edinburgh ML, merged with ideas from Hope.',
    kind: 'Direct',
  },
  {
    from: 'ml',
    to: 'caml',
    ideas: ['inference'],
    note: 'Caml was INRIA’s own dialect of ML, grown from the LCF ML tradition.',
    kind: 'Direct',
  },
  {
    from: 'ml',
    to: 'hope',
    ideas: ['inference'],
    note: 'Hope took ML’s polymorphic type system and added algebraic data types with pattern matching.',
    kind: 'Direct',
  },
  {
    from: 'ml',
    to: 'cyclone',
    ideas: ['adts'],
    note: 'Cyclone, built by ML researchers, gave C ML-style tagged unions, pattern matching and polymorphism.',
    kind: 'Direct',
  },
  {
    from: 'ml',
    to: 'typescript',
    ideas: ['adts', 'inference'],
    note: 'TypeScript’s checked unions and local inference revisit ML ideas, though its structural and deliberately unsound types work differently.',
    kind: 'Echo',
  },
  {
    from: 'ml',
    to: 'gleam',
    ideas: ['inference', 'adts'],
    note: 'Gleam brings ML-family typing to the BEAM: Hindley–Milner inference, custom types and exhaustive case.',
    kind: 'Direct',
  },
  {
    from: 'hope',
    to: 'sml',
    ideas: ['adts'],
    note: 'Standard ML’s datatype declarations and pattern matching came from Hope.',
    kind: 'Direct',
  },
  {
    from: 'hope',
    to: 'haskell',
    ideas: ['adts'],
    note: 'Hope’s algebraic data types with pattern-matching equations became central to Haskell.',
    kind: 'Direct',
  },
  {
    from: 'sml',
    to: 'cml',
    ideas: ['fibers'],
    note: 'Concurrent ML was built as a library for Standard ML of New Jersey.',
    kind: 'Direct',
  },
  {
    from: 'sml',
    to: 'react',
    ideas: ['purity'],
    note: 'According to Reason’s documentation, Jordan Walke’s first prototypes of React were written in Standard ML.',
    kind: 'Direct',
  },
  {
    from: 'sml',
    to: 'okasaki',
    ideas: ['immutability'],
    note: 'Okasaki wrote his book’s code in Standard ML, with Haskell versions in an appendix.',
    kind: 'Direct',
  },
  {
    from: 'caml',
    to: 'ocaml',
    ideas: ['inference', 'adts'],
    note: 'OCaml is Caml Light extended with objects, a richer module system and a native-code compiler.',
    kind: 'Direct',
  },
  {
    from: 'caml',
    to: 'coq',
    ideas: ['proofs'],
    note: 'Coq was implemented in Caml, and is written today in its successor, OCaml.',
    kind: 'Direct',
  },
  {
    from: 'cml',
    to: 'racket',
    ideas: ['fibers'],
    note: 'Racket’s synchronizable events are modelled on Concurrent ML’s.',
    kind: 'Direct',
  },
  {
    from: 'ocaml',
    to: 'fsharp',
    ideas: ['inference', 'adts'],
    note: 'F# began as an OCaml for .NET, keeping its syntax, inference and variant types.',
    kind: 'Direct',
  },
  {
    from: 'ocaml',
    to: 'rust',
    ideas: ['adts', 'inference'],
    note: 'Rust’s first compiler was written in OCaml, and the Rust Reference credits SML and OCaml for its algebraic types, pattern matching and inference.',
    kind: 'Direct',
  },
  {
    from: 'ocaml',
    to: 'reason',
    ideas: ['adts'],
    note: 'Reason is an alternative syntax for OCaml, sharing its compiler and type system.',
    kind: 'Direct',
  },
  {
    from: 'ocaml',
    to: 'ocaml5',
    ideas: ['effects'],
    note: 'OCaml 5 is the same language on a new multicore runtime that supports effect handlers.',
    kind: 'Direct',
  },
  {
    from: 'scala',
    to: 'spark',
    ideas: ['hof', 'immutability'],
    note: 'Spark is written in Scala, and its dataset API is Scala’s collection API stretched across a cluster.',
    kind: 'Direct',
  },
  {
    from: 'scala',
    to: 'akka',
    ideas: ['actors'],
    note: 'Akka was written in Scala, succeeding the actors library in Scala’s standard library.',
    kind: 'Direct',
  },
  {
    from: 'scala',
    to: 'scalaz',
    ideas: ['typeclasses'],
    note: 'Scalaz used Scala’s implicits to encode Haskell-style type classes.',
    kind: 'Direct',
  },
  {
    from: 'isabelle',
    to: 'fsharp',
    ideas: ['pipelines'],
    note: 'Syme credits Tobias Nipkow, who named |> for Isabelle’s ML code in May 1994, as the origin of the pipeline symbol F# made famous.',
    kind: 'Direct',
  },
  {
    from: 'fsharp',
    to: 'async-await',
    ideas: ['monads', 'continuations'],
    note: 'C#’s async/await followed F#’s async workflows of 2007, as Syme and the C# designers have described.',
    kind: 'Direct',
  },
  {
    from: 'fsharp',
    to: 'elixir',
    ideas: ['pipelines'],
    note: 'Elixir’s |> does the job of F#’s, but threads the value into the first argument rather than the last.',
    kind: 'Echo',
  },
  {
    from: 'fsharp',
    to: 'effect',
    ideas: ['pipelines'],
    note: 'Effect’s pipe threads a value through functions left to right, the habit F#’s |> made popular.',
    kind: 'Echo',
  },

  // PROOFS & DEPENDENT TYPES

  {
    from: 'automath',
    to: 'coq',
    ideas: ['proofs'],
    note: 'Coq follows the plan de Bruijn pioneered in Automath: proofs written as terms of a typed λ-calculus and checked by type checking.',
    kind: 'Echo',
  },
  {
    from: 'coq',
    to: 'lean',
    ideas: ['proofs'],
    note: 'Lean’s kernel implements a version of the Calculus of Inductive Constructions, the foundation Coq is built on.',
    kind: 'Direct',
  },
  {
    from: 'lean',
    to: 'alphaproof',
    ideas: ['proofs'],
    note: 'AlphaProof writes its proofs in Lean 4, whose kernel checks every one.',
    kind: 'Direct',
  },

  // LAZY & PURE

  {
    from: 'sasl',
    to: 'miranda',
    ideas: ['laziness'],
    note: 'Miranda descends from SASL by way of Turner’s KRC (1981).',
    kind: 'Direct',
  },
  {
    from: 'miranda',
    to: 'haskell',
    ideas: ['laziness', 'adts'],
    note: 'Haskell’s syntax and semantics drew heavily on Miranda, the most widely used lazy language when the committee met.',
    kind: 'Direct',
  },
  {
    from: 'miranda',
    to: 'clean',
    ideas: ['laziness'],
    note: 'Clean’s early syntax and lazy semantics drew on Miranda.',
    kind: 'Direct',
  },
  {
    from: 'clean',
    to: 'rust',
    ideas: ['ownership'],
    note: 'Clean’s uniqueness types, which allow updating a value in place when it has only one reference, prefigure Rust’s ownership.',
    kind: 'Echo',
  },
  {
    from: 'haskell',
    to: 'python',
    ideas: ['comprehensions'],
    note: 'Python 2.0’s list comprehensions (PEP 202) came, as its release notes say, from Haskell.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'scala',
    ideas: ['typeclasses', 'monads', 'comprehensions'],
    note: 'Scala’s for-comprehensions desugar much as Haskell’s do-notation does, and its implicits encode Haskell’s type classes.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'fsharp',
    ideas: ['monads'],
    note: 'F#’s computation expressions generalise Haskell’s do-notation, a debt Syme acknowledges in his history of F#.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'linq',
    ideas: ['monads', 'comprehensions'],
    note: 'Meijer, a long-time Haskell researcher, designed LINQ’s query syntax as monad comprehensions over SelectMany.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'rust',
    ideas: ['typeclasses'],
    note: 'The Rust Reference credits Haskell for type classes, which became Rust’s traits.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'swift',
    ideas: ['optionresult'],
    note: 'Lattner named Haskell among Swift’s influences; Swift’s Optional plays the role of Haskell’s Maybe.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'elm',
    ideas: ['purity', 'adts'],
    note: 'Elm’s compiler is written in Haskell, and its syntax is Haskell’s, simplified.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'purescript',
    ideas: ['typeclasses'],
    note: 'PureScript is written in Haskell and follows its syntax and type classes closely, with strict evaluation.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'scalaz',
    ideas: ['typeclasses', 'monads'],
    note: 'Scalaz ported Haskell’s type-class hierarchy, Functor through Monad, to Scala.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'quickcheck',
    ideas: ['testing'],
    note: 'QuickCheck is a Haskell library that uses type classes to generate random test data for any type.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'stm-paper',
    ideas: ['stm'],
    note: 'The paper designed STM for GHC, using Haskell’s types to keep I/O out of transactions.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'nix',
    ideas: ['purity', 'laziness'],
    note: 'Nix’s expression language is lazy and purely functional, like Haskell, applied to software builds.',
    kind: 'Echo',
  },
  {
    from: 'haskell',
    to: 'excel-lambda',
    ideas: ['lambda'],
    note: 'Simon Peyton Jones, a principal designer of Haskell, was among the Microsoft researchers behind LAMBDA.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'jax',
    ideas: ['purity'],
    note: 'JAX’s splittable random-number keys follow a design described for Haskell by Claessen and Pałka (2013).',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'fran',
    ideas: ['frp'],
    note: 'Fran was a Haskell library, using type classes so behaviours could be added and multiplied like numbers.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'pizza',
    ideas: ['lambda', 'adts'],
    note: 'Wadler, a Haskell designer, co-created Pizza to bring higher-order functions and algebraic data types to Java.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'curry-lang',
    ideas: ['laziness', 'logic'],
    note: 'Curry takes Haskell’s syntax and lazy evaluation and adds logic variables.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'agda',
    ideas: ['proofs'],
    note: 'Agda 2 is implemented in Haskell and borrows much of its syntax.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'idris',
    ideas: ['proofs'],
    note: 'Idris 1 was implemented in Haskell, and its syntax is deliberately close to Haskell’s.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'lean',
    ideas: ['monads', 'typeclasses'],
    note: 'Lean 4 borrowed Haskell’s do-notation, monads and type classes for programming in it.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'fp-ts',
    ideas: ['typeclasses', 'monads'],
    note: 'fp-ts ports Haskell’s type classes and data types, among them Option, Either and IO, to TypeScript.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'effect',
    ideas: ['monads'],
    note: 'Effect.gen uses generators to give TypeScript an equivalent of Haskell’s do-notation.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'ramda',
    ideas: ['pipelines'],
    note: 'Ramda’s automatic currying and right-to-left compose bring Haskell’s habit of building functions out of functions.',
    kind: 'Echo',
  },
  {
    from: 'haskell',
    to: 'fantasy-land',
    ideas: ['typeclasses', 'monads'],
    note: 'Fantasy Land writes down Haskell’s type-class laws, for Functor, Applicative, Monad and more, as a JavaScript specification.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'sanctuary',
    ideas: ['optionresult'],
    note: 'Sanctuary describes itself as inspired by Haskell, and documents every function with a Haskell-style type signature.',
    kind: 'Direct',
  },
  {
    from: 'haskell',
    to: 'mostly-adequate',
    ideas: ['monads'],
    note: 'The guide explains its JavaScript with Haskell-style type signatures and teaches Haskell’s functors and monads.',
    kind: 'Direct',
  },
  {
    from: 'quickcheck',
    to: 'effect',
    ideas: ['testing'],
    note: 'Effect can derive fast-check arbitraries from a Schema, and fast-check is a QuickCheck-style library for JavaScript.',
    kind: 'Direct',
  },
  {
    from: 'quickcheck',
    to: 'clojure',
    ideas: ['testing'],
    note: 'Clojure’s test.check, which began as Reid Draper’s simple-check, describes itself as inspired by QuickCheck.',
    kind: 'Direct',
  },
  {
    from: 'purescript',
    to: 'fp-ts',
    ideas: ['typeclasses'],
    note: 'fp-ts names PureScript, with Haskell and Scala, among its inspirations.',
    kind: 'Direct',
  },

  // EFFECT SYSTEMS

  {
    from: 'scalaz',
    to: 'cats-effect',
    ideas: ['monads'],
    note: 'Typelevel’s Cats, and then Cats Effect, grew out of the Scalaz community as a more modular take on the same ideas.',
    kind: 'Direct',
  },
  {
    from: 'scalaz',
    to: 'zio',
    ideas: ['monads', 'fibers'],
    note: 'ZIO began as John De Goes’s IO type for Scalaz 8 and was split out as its own library in 2018.',
    kind: 'Direct',
  },
  {
    from: 'cats-effect',
    to: 'zio',
    ideas: ['fibers'],
    note: 'Cats Effect and ZIO competed and converged on fiber-based runtimes, interruption and resource safety.',
    kind: 'Echo',
  },
  {
    from: 'zio',
    to: 'effect',
    ideas: ['fibers', 'optionresult', 'stm', 'supervision'],
    note: 'Effect’s core was ported from ZIO, using its source as a reference: Effect<A, E, R> is ZIO[R, E, A] reordered, with fibers, STM, layers and structured concurrency.',
    kind: 'Direct',
  },
  {
    from: 'fp-ts',
    to: 'effect',
    ideas: ['typeclasses', 'optionresult'],
    note: 'Canti, fp-ts’s author, joined Effect and wrote its Schema module in the line of his io-ts.',
    kind: 'Direct',
  },
  {
    from: 'effect',
    to: 'foldkit',
    ideas: ['monads'],
    note: 'Foldkit runs The Elm Architecture on Effect: commands are Effects and the model is described by a Schema.',
    kind: 'Direct',
  },
  {
    from: 'async-await',
    to: 'typescript',
    ideas: ['continuations'],
    note: 'TypeScript, also led by Hejlsberg, supported async/await in 2015, before JavaScript standardised it in ES2017.',
    kind: 'Direct',
  },
  {
    from: 'async-await',
    to: 'swift',
    ideas: ['continuations'],
    note: 'Swift 5.5 (2021) adopted async/await, which Lattner’s 2017 concurrency manifesto had proposed with C# among its precedents.',
    kind: 'Direct',
  },
  {
    from: 'async-await',
    to: 'effect',
    ideas: ['monads'],
    note: 'Effect.gen reads like async/await but works for any effect, carrying typed errors, services and interruption as well as waiting.',
    kind: 'Echo',
  },
  {
    from: 'erlang',
    to: 'effect',
    ideas: ['supervision', 'fibers'],
    note: 'Effect’s fibers, scopes and supervisors carry Erlang’s idea that failure should be contained and handled structurally.',
    kind: 'Echo',
  },
  {
    from: 'fluture',
    to: 'effect',
    ideas: ['laziness'],
    note: 'Like a Fluture Future, an Effect is a lazy description that runs only when executed and can be interrupted, unlike an eager Promise.',
    kind: 'Echo',
  },
  {
    from: 'ramda',
    to: 'effect',
    ideas: ['pipelines'],
    note: 'Effect’s functions come in data-first and data-last forms, so they compose in pipe the way Ramda’s curried functions do.',
    kind: 'Echo',
  },

  // REACTIVE & DATAFLOW

  {
    from: 'lucid',
    to: 'lustre',
    ideas: ['frp'],
    note: 'Lustre was conceived as a synchronous restriction of Lucid’s dataflow model, with one value per clock tick.',
    kind: 'Direct',
  },
  {
    from: 'esterel',
    to: 'lustre',
    ideas: ['frp'],
    note: 'Esterel and Lustre are sibling French synchronous languages, one imperative and one dataflow, resting on the same synchronous hypothesis.',
    kind: 'Echo',
  },
  {
    from: 'visicalc',
    to: 'excel-lambda',
    ideas: ['frp', 'lambda'],
    note: 'Excel inherits the spreadsheet model VisiCalc created, and LAMBDA finally let its formulas define functions.',
    kind: 'Direct',
  },
  {
    from: 'visicalc',
    to: 'signals',
    ideas: ['frp'],
    note: 'A signal is a spreadsheet cell for the DOM: change it and only the formulas that read it recompute.',
    kind: 'Echo',
  },
  {
    from: 'rx',
    to: 'signals',
    ideas: ['frp'],
    note: 'Signals and observables both model changing values, but a signal holds a current value and tracks its readers without explicit subscriptions.',
    kind: 'Echo',
  },
  {
    from: 'rx',
    to: 'bacon',
    ideas: ['frp'],
    note: 'Bacon.js offered Rx-style stream combinators while separating discrete EventStreams from Properties that always hold a value.',
    kind: 'Echo',
  },
  {
    from: 'elm',
    to: 'redux',
    ideas: ['tea'],
    note: 'Redux’s documentation credits Elm: a reducer is Elm’s update, taking the state and an action and returning the next state.',
    kind: 'Direct',
  },
  {
    from: 'elm',
    to: 'react',
    ideas: ['tea'],
    note: 'Elm and React, a year apart, both describe the UI as a function of state and let the runtime work out the changes.',
    kind: 'Echo',
  },
  {
    from: 'elm',
    to: 'bubbletea',
    ideas: ['tea'],
    note: 'Bubble Tea’s README says it is based on The Elm Architecture: Init, Update and View.',
    kind: 'Direct',
  },
  {
    from: 'elm',
    to: 'foldkit',
    ideas: ['tea'],
    note: 'Foldkit implements The Elm Architecture, with the same model, messages, update, view and subscriptions.',
    kind: 'Direct',
  },
  {
    from: 'react',
    to: 'redux',
    ideas: ['purity'],
    note: 'Redux was built to manage state in React apps, with react-redux connecting the store to components.',
    kind: 'Direct',
  },
  {
    from: 'react',
    to: 'react-hooks',
    ideas: ['tea'],
    note: 'Hooks let React’s function components hold state and effects, replacing most class components.',
    kind: 'Direct',
  },
  {
    from: 'react',
    to: 'signals',
    ideas: ['frp'],
    note: 'Signals grew partly as a reaction to React’s re-render-and-diff model, updating only what depends on a changed value.',
    kind: 'Echo',
  },
  {
    from: 'react',
    to: 'swiftui',
    ideas: ['purity'],
    note: 'SwiftUI shares React’s idea that a view is a function of state, recomputed and diffed by the framework.',
    kind: 'Echo',
  },
  {
    from: 'react',
    to: 'reason',
    ideas: ['purity'],
    note: 'Reason was created by React’s author, and ReasonReact gave React typed OCaml bindings.',
    kind: 'Direct',
  },
  {
    from: 'immutable-js',
    to: 'redux',
    ideas: ['immutability'],
    note: 'Redux’s documentation lists Immutable.js as prior art, and the two were often used together.',
    kind: 'Direct',
  },
  {
    from: 'redux',
    to: 'react-hooks',
    ideas: ['tea'],
    note: 'React’s useReducer hook works like a Redux reducer, as React’s own documentation points out.',
    kind: 'Direct',
  },

  // ARRAYS & DATA

  {
    from: 'apl',
    to: 'j',
    ideas: ['arrays'],
    note: 'Iverson designed J with Roger Hui as APL’s successor, keeping its array semantics but spelling it in ASCII.',
    kind: 'Direct',
  },
  {
    from: 'apl',
    to: 'k',
    ideas: ['arrays'],
    note: 'K descends from APL by way of Whitney’s A+, keeping whole-array primitives in ASCII.',
    kind: 'Direct',
  },
  {
    from: 'apl',
    to: 'backus-fp',
    ideas: ['hof', 'arrays'],
    note: 'Backus’s lecture discusses Iverson’s APL and its operators, functions that take functions, as a step toward function-level programming.',
    kind: 'Direct',
  },
  {
    from: 'apl',
    to: 'numpy',
    ideas: ['arrays'],
    note: 'NumPy’s whole-array operations and reductions are the APL way of thinking, arrived at by way of MATLAB and Numeric.',
    kind: 'Echo',
  },
  {
    from: 'matlab',
    to: 'numpy',
    ideas: ['arrays'],
    note: 'NumPy set out to make MATLAB users feel at home, and its documentation includes a guide written for them.',
    kind: 'Direct',
  },
  {
    from: 'matlab',
    to: 'julia',
    ideas: ['arrays'],
    note: 'Julia’s announcement asked for MATLAB’s familiar mathematical notation, and its array syntax follows MATLAB’s.',
    kind: 'Direct',
  },
  {
    from: 'numpy',
    to: 'jax',
    ideas: ['arrays'],
    note: 'jax.numpy mirrors NumPy’s API, so ordinary array code can be differentiated, vectorised and compiled.',
    kind: 'Direct',
  },

  // ACTORS & CONCURRENCY

  {
    from: 'erlang',
    to: 'otp',
    ideas: ['supervision'],
    note: 'OTP is Erlang’s standard set of libraries and design principles: supervisors, gen_server and releases.',
    kind: 'Direct',
  },
  {
    from: 'erlang',
    to: 'akka',
    ideas: ['actors', 'supervision'],
    note: 'Akka brought Erlang’s actors, location transparency and supervision hierarchies to the JVM.',
    kind: 'Direct',
  },
  {
    from: 'erlang',
    to: 'elixir',
    ideas: ['actors', 'supervision'],
    note: 'Elixir runs on the Erlang VM, calls Erlang libraries directly and uses OTP as is.',
    kind: 'Direct',
  },
  {
    from: 'erlang',
    to: 'gleam',
    ideas: ['actors'],
    note: 'Gleam compiles to Erlang and runs on the BEAM, using its lightweight processes.',
    kind: 'Direct',
  },
  {
    from: 'erlang',
    to: 'rust',
    ideas: ['actors'],
    note: 'The Rust Reference credits Erlang for message passing, linked thread failure and lightweight concurrency, ideas central to early Rust.',
    kind: 'Direct',
  },
  {
    from: 'otp',
    to: 'akka',
    ideas: ['supervision'],
    note: 'Akka’s supervision hierarchies are modelled on OTP’s supervisors.',
    kind: 'Direct',
  },
  {
    from: 'otp',
    to: 'elixir',
    ideas: ['supervision'],
    note: 'Elixir’s Supervisor and GenServer modules are thin wrappers over OTP’s behaviours.',
    kind: 'Direct',
  },

  // LOGIC & RELATIONS

  {
    from: 'planner',
    to: 'prolog',
    ideas: ['logic'],
    note: 'Prolog emerged from debates over Planner’s procedural approach to theorem proving; Kowalski’s procedural reading of logic was a reply.',
    kind: 'Direct',
  },
  {
    from: 'planner',
    to: 'actor-model',
    ideas: ['actors'],
    note: 'Hewitt generalised Planner’s pattern-directed invocation into actors, where everything happens by sending a message.',
    kind: 'Direct',
  },
  {
    from: 'prolog',
    to: 'erlang',
    ideas: ['logic'],
    note: 'Erlang’s first interpreter was written in Prolog, and its clauses, pattern matching, full stops and capitalised variables show it.',
    kind: 'Direct',
  },
  {
    from: 'prolog',
    to: 'datalog',
    ideas: ['logic'],
    note: 'Datalog is Prolog restricted to function-free clauses, so every query terminates.',
    kind: 'Direct',
  },
  {
    from: 'prolog',
    to: 'curry-lang',
    ideas: ['logic'],
    note: 'Curry adds Prolog-style logic variables and search to a lazy functional language.',
    kind: 'Direct',
  },
  {
    from: 'prolog',
    to: 'minikanren',
    ideas: ['logic'],
    note: 'miniKanren is relational programming in Prolog’s spirit, but with a complete interleaving search and no cut.',
    kind: 'Echo',
  },
  {
    from: 'prolog',
    to: 'typeclasses-paper',
    ideas: ['logic'],
    note: 'Resolving instances is a small logic program: the compiler backward-chains through instance declarations much as Prolog does through clauses.',
    kind: 'Echo',
  },
  {
    from: 'sql',
    to: 'linq',
    ideas: ['comprehensions'],
    note: 'LINQ borrowed SQL’s clauses but moved from to the front, so the editor knows the type before you write select.',
    kind: 'Direct',
  },
  {
    from: 'datalog',
    to: 'datomic',
    ideas: ['logic'],
    note: 'Datomic’s query language is Datalog, written as Clojure data.',
    kind: 'Direct',
  },
  {
    from: 'datalog',
    to: 'codeql',
    ideas: ['logic'],
    note: 'QL compiles to Datalog, and Semmle’s engine evaluates it over a database of facts about the code.',
    kind: 'Direct',
  },

  // JAVASCRIPT’S FUNCTIONAL LIBRARIES

  {
    from: 'underscore',
    to: 'lodash',
    ideas: ['hof'],
    note: 'Lodash began in 2012 as a fork of Underscore and kept its API so it could serve as a drop-in replacement.',
    kind: 'Direct',
  },
  {
    from: 'underscore',
    to: 'ramda',
    ideas: ['pipelines'],
    note: 'Ramda offers much of Underscore’s toolkit with the argument order reversed, data last, so every function curries and composes.',
    kind: 'Echo',
  },
  {
    from: 'ramda',
    to: 'sanctuary',
    ideas: ['purity'],
    note: 'Sanctuary describes itself as stricter than Ramda, offering a similar suite of functions that never return null or throw.',
    kind: 'Direct',
  },
  {
    from: 'fantasy-land',
    to: 'folktale',
    ideas: ['monads'],
    note: 'Folktale’s Maybe, Either and Task implemented the Fantasy Land specification.',
    kind: 'Direct',
  },
  {
    from: 'fantasy-land',
    to: 'sanctuary',
    ideas: ['typeclasses'],
    note: 'Sanctuary’s types implement Fantasy Land, and its functions accept any compliant type.',
    kind: 'Direct',
  },
  {
    from: 'fantasy-land',
    to: 'fluture',
    ideas: ['monads'],
    note: 'Fluture’s Future implements Fantasy Land’s Functor, Bifunctor and Monad, among others.',
    kind: 'Direct',
  },
  {
    from: 'fantasy-land',
    to: 'fp-ts',
    ideas: ['typeclasses'],
    note: 'fp-ts encodes the same Functor-to-Monad hierarchy and laws, but checks them with static types rather than method names.',
    kind: 'Echo',
  },
  {
    from: 'folktale',
    to: 'fluture',
    ideas: ['monads', 'laziness'],
    note: 'Fluture’s Future and Folktale’s Task are both lazy, forkable alternatives to Promise.',
    kind: 'Echo',
  },
  {
    from: 'mostly-adequate',
    to: 'fp-ts',
    ideas: ['monads'],
    note: 'The guide prepared a generation of JavaScript developers for the Option, Either and Task that fp-ts then made type-safe.',
    kind: 'Echo',
  },
]
