import type { Star } from '../domain/star'

// Every star in the galaxy. Years are births: first paper, first
// implementation or first public release, whichever is most often cited.
// Fields are disciplines outside programming that fed ideas in.

export const stars: ReadonlyArray<Star> = [
  // FOUNDATIONS & FIELDS

  {
    id: 'field-logic',
    name: 'Mathematical Logic',
    kind: 'Field',
    constellation: 'Foundations',
    year: 1928,
    people: 'David Hilbert, Wilhelm Ackermann, Kurt Gödel',
    epithet: 'The question that invented computation',
    blurb:
      'In 1928 Hilbert and Ackermann asked for a mechanical procedure to decide whether any statement of logic is provable: the Entscheidungsproblem. Gödel’s incompleteness theorems (1931) shook the programme, and in 1936 Church and Turing each proved no such procedure exists. To do it, they first had to define what “mechanical” means.',
    ideas: ['proofs', 'logic'],
    magnitude: 1,
  },
  {
    id: 'combinatory-logic',
    name: 'Combinatory Logic',
    kind: 'Theory',
    constellation: 'Foundations',
    year: 1924,
    people: 'Moses Schönfinkel, Haskell Curry',
    epithet: 'Computation without a single variable',
    blurb:
      'Schönfinkel showed in 1924 that a handful of combinators, two of which (now called S and K) suffice, can express any function without naming a variable; Curry rebuilt the theory from 1930. Turning a many-argument function into one-argument steps was Schönfinkel’s trick, yet we call it currying. In 1979 David Turner compiled SASL into combinators to run lazy programs.',
    ideas: ['lambda', 'pipelines'],
    magnitude: 2,
  },
  {
    id: 'lambda-calculus',
    name: 'λ-calculus',
    kind: 'Theory',
    constellation: 'Foundations',
    year: 1936,
    people: 'Alonzo Church',
    epithet: 'The calculus where everything is a function',
    blurb:
      'Church’s calculus has three things: variables, functions written λx.…, and application. Numbers, booleans and recursion can all be encoded with nothing else. Church developed it in the early 1930s as a foundation for logic, then in 1936 used it to prove the Entscheidungsproblem unsolvable. Turing, who reached the same answer by another route, went to Princeton to do his PhD under Church.',
    ideas: ['lambda'],
    magnitude: 1,
  },
  {
    id: 'typed-lambda',
    name: 'Simply Typed λ-calculus',
    kind: 'Theory',
    constellation: 'Foundations',
    year: 1940,
    people: 'Alonzo Church',
    epithet: 'λ-calculus with a type on every term',
    blurb:
      'Untyped λ-calculus can loop forever and encode paradoxes. In 1940 Church gave every variable a simple type, which rules out self-application like x x and guarantees that every well-typed term reduces to a normal form. Nearly every typed functional language, and the Curry–Howard correspondence, starts from this system.',
    ideas: ['proofs'],
    magnitude: 3,
  },
  {
    id: 'turing-machine',
    name: 'Turing Machines',
    kind: 'Theory',
    constellation: 'Imperative',
    year: 1936,
    people: 'Alan Turing',
    epithet: 'A tape, a head, a table of rules',
    blurb:
      '“On Computable Numbers” (1936) modelled a human computer as a machine with an endless tape and a finite table of rules, and showed that one universal machine can imitate any other. In an appendix Turing proved his machines compute exactly Church’s λ-definable functions. Functions on one side, state and steps on the other: the two roots of programming.',
    ideas: [],
    magnitude: 2,
  },
  {
    id: 'field-proof',
    name: 'Constructive Logic',
    kind: 'Field',
    constellation: 'Proof',
    year: 1930,
    people: 'L. E. J. Brouwer, Arend Heyting, Gerhard Gentzen',
    epithet: 'A proof must show how',
    blurb:
      'Brouwer’s intuitionists refused to believe something exists unless you can construct it. Heyting formalised their logic in 1930, and the Brouwer–Heyting–Kolmogorov reading says a proof of “A implies B” is a method turning proofs of A into proofs of B: a function. Gentzen’s natural deduction (1934) gave proofs the tree shape type checkers still use.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'field-category',
    name: 'Category Theory',
    kind: 'Field',
    constellation: 'Lazy',
    year: 1945,
    people: 'Samuel Eilenberg, Saunders Mac Lane',
    epithet: 'The mathematics of composition',
    blurb:
      'Eilenberg and Mac Lane introduced categories, functors and natural transformations in 1945 to compare structures across algebra and topology; it was affectionately called “general abstract nonsense”. Monads appeared in the late 1950s as Godement’s “standard constructions”. Decades later the same definitions became Functor and Monad in Haskell.',
    ideas: ['monads', 'pipelines'],
    magnitude: 1,
  },
  {
    id: 'field-ai',
    name: 'Symbolic AI',
    kind: 'Field',
    constellation: 'Lisp',
    year: 1956,
    people: 'John McCarthy, Marvin Minsky, Allen Newell, Herbert Simon',
    epithet: 'Intelligence as symbols and search',
    blurb:
      'McCarthy coined “artificial intelligence” in the 1955 proposal for a summer workshop at Dartmouth, held in 1956. The bet was that thinking is symbol manipulation: proving theorems, parsing sentences, planning moves. That bet needed languages for lists, trees and search, and gave us Lisp, garbage collection, Planner and Prolog.',
    ideas: ['logic', 'homoiconicity'],
    magnitude: 1,
  },
  {
    id: 'field-notation',
    name: 'Mathematical Notation',
    kind: 'Field',
    constellation: 'Array',
    year: 1957,
    people: 'Kenneth Iverson',
    epithet: 'Notation as a tool of thought',
    blurb:
      'Teaching at Harvard in the late 1950s, Iverson found ordinary mathematical notation inconsistent and invented his own for describing algorithms on whole arrays. It was meant for blackboards and books, not machines; in 1964 it was used to describe IBM’s System/360 formally. His 1979 Turing Award lecture was titled “Notation as a Tool of Thought”.',
    ideas: ['arrays'],
    magnitude: 2,
  },
  {
    id: 'field-concurrency',
    name: 'Concurrency Theory',
    kind: 'Field',
    constellation: 'Actors',
    year: 1962,
    people: 'Carl Adam Petri, Edsger Dijkstra, Tony Hoare, Robin Milner',
    epithet: 'What happens when things happen at once',
    blurb:
      'Petri’s 1962 dissertation drew concurrent systems as tokens moving through places and transitions. Dijkstra’s semaphores, Hoare’s CSP (1978), Milner’s CCS (1980) and the π-calculus followed, each trying to make parallel programs something you can reason about. Their vocabulary of processes, channels and transactions now lives in Go, Erlang and STM.',
    ideas: ['actors', 'stm'],
    magnitude: 2,
  },
  {
    id: 'field-education',
    name: 'Children & Learning',
    kind: 'Field',
    constellation: 'Objects',
    year: 1967,
    people: 'Seymour Papert, Cynthia Solomon, Alan Kay',
    epithet: 'Programming as a way to think',
    blurb:
      'Papert, who had worked with Jean Piaget, argued that children learn best by building things, and Logo gave them a turtle to command. Watching children program in Logo in 1968 helped Alan Kay imagine the Dynabook, a personal computer for children, which became the brief for Smalltalk. The thread runs on through Racket’s teaching languages, SICP and Scratch.',
    ideas: ['repl', 'objects'],
    magnitude: 2,
  },
  {
    id: 'field-databases',
    name: 'Databases & Relational Algebra',
    kind: 'Field',
    constellation: 'Logic',
    year: 1970,
    people: 'Edgar F. Codd',
    epithet: 'Data as relations, queries as logic',
    blurb:
      'Codd’s 1970 paper “A Relational Model of Data for Large Shared Data Banks” replaced pointer-chasing through records with tables and a small algebra over them. You say what you want and the system works out how to fetch it. That declarative bargain produced SQL, fed Datalog and shaped LINQ.',
    ideas: ['logic'],
    magnitude: 2,
  },
  {
    id: 'field-control',
    name: 'Control Systems & Avionics',
    kind: 'Field',
    constellation: 'Reactive',
    year: 1980,
    people: 'Gérard Berry, Paul Caspi, Nicolas Halbwachs',
    epithet: 'Software that must react on time',
    blurb:
      'Flight controllers and railway interlocks read sensors and update outputs in a fixed rhythm, and control engineers already drew them as block diagrams of signals. In the early 1980s French researchers turned that habit into synchronous languages, which treat each reaction as taking no time at all. Their descendant SCADE is used for Airbus flight-control software.',
    ideas: ['frp'],
    magnitude: 2,
  },
  {
    id: 'field-telecom',
    name: 'Telecom & Fault Tolerance',
    kind: 'Field',
    constellation: 'Actors',
    year: 1982,
    people: 'Ericsson Computer Science Laboratory',
    epithet: 'Phone switches that must never stop',
    blurb:
      'A telephone exchange juggles thousands of independent calls, must be upgraded without dropping any of them, and treats hardware failure as routine. In the early 1980s Ericsson’s Computer Science Lab tested existing languages against those demands. None fit, so they built Erlang; Ericsson’s AXD301 switch was famously reported to reach “nine nines” of availability.',
    ideas: ['supervision', 'actors'],
    magnitude: 2,
  },
  {
    id: 'field-finance',
    name: 'Quantitative Finance',
    kind: 'Field',
    constellation: 'Array',
    year: 1973,
    people:
      'Fischer Black, Myron Scholes, Robert Merton; later Arthur Whitney, Jane Street',
    epithet: 'Money that has to be computed',
    blurb:
      'The Black–Scholes model (1973) turned option pricing into computation, and trading floors became some of programming’s most demanding customers. Dan Bricklin dreamed up VisiCalc while watching a business-school professor redo a financial model by hand. Finance has since bankrolled Arthur Whitney’s terse array languages, Jane Street’s OCaml and Standard Chartered’s in-house Haskell.',
    ideas: ['arrays'],
    magnitude: 3,
  },

  // THEORIES

  {
    id: 'hindley-milner',
    name: 'Hindley–Milner',
    kind: 'Theory',
    constellation: 'Ml',
    year: 1969,
    people: 'Roger Hindley, Robin Milner, Luis Damas',
    epithet: 'Every expression has a most general type',
    blurb:
      'Hindley showed in 1969 that terms of combinatory logic have a principal type, a most general one from which every other follows. Milner independently rediscovered the idea for ML in 1978 with an inference algorithm, W, and Damas proved it complete in 1982. It is why a whole OCaml or Haskell program can carry no type annotations.',
    ideas: ['inference'],
    magnitude: 2,
  },
  {
    id: 'curry-howard',
    name: 'Curry–Howard',
    kind: 'Theory',
    constellation: 'Proof',
    year: 1969,
    people: 'Haskell Curry, William Howard',
    epithet: 'Propositions are types; proofs are programs',
    blurb:
      'Curry noticed in the 1930s that the types of his combinators read like axioms of logic. Howard’s 1969 manuscript, passed around for a decade before it was published in 1980, made the match exact: a function of type A → B is a proof that A implies B, and running a program simplifies a proof. Rocq, Agda, Idris and Lean are built on it.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'system-f',
    name: 'System F',
    kind: 'Theory',
    constellation: 'Ml',
    year: 1972,
    people: 'Jean-Yves Girard, John Reynolds',
    epithet: 'Functions that take types as arguments',
    blurb:
      'Girard, working on proof theory, and Reynolds, working on programming languages, found the same calculus independently (1972 and 1974): λ-calculus in which a term can be abstracted over a type. It is the theory behind generics. GHC still compiles every Haskell program to Core, a typed intermediate language extended from System F.',
    ideas: ['inference'],
    magnitude: 3,
  },
  {
    id: 'martin-lof',
    name: 'Intuitionistic Type Theory',
    kind: 'Theory',
    constellation: 'Proof',
    year: 1972,
    people: 'Per Martin-Löf',
    epithet: 'Mathematics you can run',
    blurb:
      'Martin-Löf designed a type theory as a foundation for constructive mathematics, in which types can depend on values: a vector’s type can mention its length. Girard found a paradox in his first version, which had a type of all types. The repair stacked types into a hierarchy of universes, the levels you still meet as Set₁ in Agda and Type 1 in Lean.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'call-by-need',
    name: 'Call-by-need',
    kind: 'Theory',
    constellation: 'Lazy',
    year: 1971,
    people:
      'Christopher Wadsworth; Peter Henderson & James Morris; Daniel Friedman & David Wise',
    epithet: 'Evaluate once, and only when needed',
    blurb:
      'Wadsworth’s 1971 thesis showed how to reduce λ-terms as a shared graph, so an argument is evaluated at most once and only if it is used. In 1976 two papers carried the idea into list processing, one of them titled “CONS Should Not Evaluate Its Arguments”. Lazy lists made infinite data ordinary, and Haskell made the strategy its default.',
    ideas: ['laziness'],
    magnitude: 3,
  },
  {
    id: 'actor-model',
    name: 'Actor Model',
    kind: 'Theory',
    constellation: 'Actors',
    year: 1973,
    people: 'Carl Hewitt, Peter Bishop, Richard Steiger',
    epithet: 'Everything is an actor sending messages',
    blurb:
      'Hewitt, Bishop and Steiger’s 1973 paper, written for an AI conference, modelled all computation as actors that receive a message, then send messages, create actors and decide how to handle the next one. There is no shared state at all. Trying to understand it, Sussman and Steele wrote Scheme; Erlang, Akka and Swift’s actors later arrived at the same shape.',
    ideas: ['actors'],
    magnitude: 1,
  },
  {
    id: 'csp',
    name: 'CSP',
    kind: 'Theory',
    constellation: 'Actors',
    year: 1978,
    people: 'Tony Hoare',
    epithet: 'Processes that meet to communicate',
    blurb:
      'Hoare’s 1978 paper “Communicating Sequential Processes” made input and output primitive: independent processes synchronise by handing values directly to one another. Named channels arrived with the 1985 book, by which time CSP had become an algebra for proving properties of concurrent systems. Rob Pike carried it through Newsqueak and Limbo into Go.',
    ideas: ['actors', 'fibers'],
    magnitude: 2,
  },
  {
    id: 'backus-fp',
    name: 'Backus’s FP',
    kind: 'Theory',
    constellation: 'Array',
    year: 1977,
    people: 'John Backus',
    epithet: 'Fortran’s creator asks to be liberated',
    blurb:
      'Backus, who had led the Fortran team, used his 1977 Turing Award lecture to ask “Can Programming Be Liberated from the von Neumann Style?”. He attacked word-at-a-time assignment and proposed FP: programs built from functions with combining forms like composition and apply-to-all, and no variables. Coming from him, the case for functional programming carried weight.',
    ideas: ['pipelines', 'hof'],
    magnitude: 2,
  },
  {
    id: 'linear-logic',
    name: 'Linear Logic',
    kind: 'Theory',
    constellation: 'Proof',
    year: 1987,
    people: 'Jean-Yves Girard',
    epithet: 'Logic where assumptions get used up',
    blurb:
      'In classical logic you can use an assumption as often as you like. Girard’s 1987 linear logic treats assumptions as resources consumed exactly once, with an explicit marker for the ones you may copy. Read as types, that describes a file handle or buffer used once and then gone: the theory behind Linear Haskell and, in its relaxed affine form, Rust’s moves.',
    ideas: ['ownership'],
    magnitude: 3,
  },
  {
    id: 'moggi',
    name: 'Computational Monads',
    kind: 'Theory',
    constellation: 'Effects',
    year: 1989,
    people: 'Eugenio Moggi; Philip Wadler',
    epithet: 'Side effects, modelled as a monad',
    blurb:
      'Moggi’s 1989 paper, expanded as “Notions of Computation and Monads” (1991), showed that state, exceptions, nondeterminism and continuations share one structure from category theory: a monad. He meant it for semantics. Wadler saw it could structure programs, and his papers of 1990–92 put monads on the road to Haskell, Promise.then and Effect.',
    ideas: ['monads'],
    magnitude: 1,
  },
  {
    id: 'typeclasses-paper',
    name: 'Type Classes',
    kind: 'Theory',
    constellation: 'Lazy',
    year: 1989,
    people: 'Philip Wadler, Stephen Blott',
    epithet: 'Overloading, done with types and dictionaries',
    blurb:
      'Wadler and Blott’s POPL 1989 paper “How to make ad-hoc polymorphism less ad hoc” proposed classes like Eq and Num: a type joins a class by supplying an instance, and the compiler quietly passes the right dictionary of functions. Written as Haskell was being designed, the idea now underlies Rust traits, Scala givens, Lean instances and fp-ts.',
    ideas: ['typeclasses'],
    magnitude: 2,
  },
  {
    id: 'pi-calculus',
    name: 'π-calculus',
    kind: 'Theory',
    constellation: 'Actors',
    year: 1992,
    people: 'Robin Milner, Joachim Parrow, David Walker',
    epithet: 'Processes that pass channels around',
    blurb:
      'Milner had already given concurrency a calculus in CCS (1980). The π-calculus (published 1992) added one twist: channel names can themselves be sent over channels, so the network of who talks to whom changes as the program runs. Milner’s 1991 Turing Award cited three achievements: LCF, ML and CCS.',
    ideas: ['actors'],
    magnitude: 3,
  },
  {
    id: 'fran',
    name: 'Fran',
    kind: 'Theory',
    constellation: 'Reactive',
    year: 1997,
    people: 'Conal Elliott, Paul Hudak',
    epithet: 'Animations as functions of time',
    blurb:
      'Elliott and Hudak’s ICFP 1997 paper “Functional Reactive Animation” made behaviours (values that vary continuously over time) and events into first-class Haskell values. You could write wiggle = sin (pi * time) and get something that moves. It launched functional reactive programming, and values-over-time spread from there to Elm, Rx and signals.',
    ideas: ['frp'],
    magnitude: 2,
  },
  {
    id: 'okasaki',
    name: 'Persistent Data Structures',
    kind: 'Theory',
    constellation: 'Lazy',
    year: 1998,
    people: 'Chris Okasaki, Phil Bagwell',
    epithet: 'Update by sharing, never by overwriting',
    blurb:
      'Okasaki’s book Purely Functional Data Structures (1998), from his 1996 thesis, showed that immutable queues, heaps and trees can be fast, often by using laziness to spread out expensive work. Phil Bagwell’s hash array mapped tries (2001) did the same for maps. Clojure, Scala and Immutable.js all build on their work.',
    ideas: ['immutability'],
    magnitude: 2,
  },
  {
    id: 'algebraic-effects',
    name: 'Algebraic Effects',
    kind: 'Theory',
    constellation: 'Effects',
    year: 2003,
    people: 'Gordon Plotkin, John Power, Matija Pretnar',
    epithet: 'Effects as operations; handlers give meaning',
    blurb:
      'Plotkin and Power (2003) described effects not as a monad wrapping values but as operations, like get, put or throw, obeying equations. Plotkin and Pretnar added handlers in 2009: code performs an operation, a handler further up decides what it means, and the handler may resume the code where it stopped. Think of exceptions you can return from.',
    ideas: ['effects'],
    magnitude: 2,
  },
  {
    id: 'stm-paper',
    name: 'Composable Memory Transactions',
    kind: 'Theory',
    constellation: 'Lazy',
    year: 2005,
    people: 'Tim Harris, Simon Marlow, Simon Peyton Jones, Maurice Herlihy',
    epithet: 'Atomic blocks that compose',
    blurb:
      'Locks don’t compose: two correct pieces of locking code can deadlock together. This PPoPP 2005 paper gave Haskell memory transactions instead, with retry to block until something changes and orElse to try an alternative. Haskell’s types kept irreversible I/O out of transactions, which is what made rolling them back safe.',
    ideas: ['stm'],
    magnitude: 3,
  },
  {
    id: 'sicp',
    name: 'SICP',
    kind: 'Theory',
    constellation: 'Lisp',
    year: 1985,
    people: 'Harold Abelson, Gerald Jay Sussman, Julie Sussman',
    epithet: 'The wizard book',
    blurb:
      'Structure and Interpretation of Computer Programs is the textbook of MIT’s introductory course 6.001, which taught it in Scheme for over two decades. It climbs from procedures to a Scheme interpreter written in Scheme and a compiler for a register machine. The wizard on the cover gave it its nickname; a JavaScript edition appeared in 2022.',
    ideas: ['lambda'],
    magnitude: 3,
  },
  {
    id: 'mapreduce',
    name: 'MapReduce',
    kind: 'Theory',
    constellation: 'Array',
    year: 2004,
    people: 'Jeffrey Dean, Sanjay Ghemawat',
    epithet: 'Lisp’s map and reduce, over thousands of machines',
    blurb:
      'Dean and Ghemawat’s OSDI 2004 paper described how Google ran jobs across thousands of commodity machines: you write a map function and a reduce function, and the framework handles partitioning, scheduling and failure. The paper says the abstraction was inspired by the map and reduce primitives of Lisp and other functional languages. Hadoop cloned it in 2006.',
    ideas: ['hof'],
    magnitude: 2,
  },

  // LISP & SCHEME

  {
    id: 'ipl',
    name: 'IPL',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1956,
    people: 'Allen Newell, Cliff Shaw, Herbert Simon',
    epithet: 'The first list-processing language',
    blurb:
      'Newell, Shaw and Simon built the Information Processing Language at RAND to write the Logic Theorist, which proved 38 of the first 52 theorems in chapter 2 of Principia Mathematica. IPL introduced linked lists and list processing, in a notation close to assembly language. McCarthy kept the lists and wanted a far cleaner language around them.',
    ideas: ['logic'],
    magnitude: 3,
  },
  {
    id: 'lisp',
    name: 'Lisp',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1958,
    people: 'John McCarthy, Steve Russell',
    epithet: 'Code is data, and data is a list',
    blurb:
      'McCarthy designed Lisp at MIT for AI research and described eval as a theoretical exercise. Steve Russell realised it could be hand-coded and so produced the first Lisp interpreter, on an IBM 704, whose address and decrement register fields gave us car and cdr. Garbage collection was invented so Lisp’s lists could be reclaimed automatically.',
    ideas: ['lambda', 'gc', 'homoiconicity', 'repl', 'hof'],
    magnitude: 1,
  },
  {
    id: 'maclisp',
    name: 'MacLisp',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1966,
    people: 'Project MAC, MIT',
    epithet: 'The Lisp of MIT’s AI Lab',
    blurb:
      'Named for MIT’s Project MAC, not any Apple product, MacLisp ran on the PDP-6 and PDP-10 and hosted most of the lab’s AI work, from Macsyma to SHRDLU. Its compiler produced numerical code that could compete with Fortran. Scheme was first written in it, and it was the main ancestor of Common Lisp and Emacs Lisp.',
    ideas: ['homoiconicity'],
    magnitude: 3,
  },
  {
    id: 'logo',
    name: 'Logo',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1967,
    people: 'Wally Feurzeig, Seymour Papert, Cynthia Solomon',
    epithet: 'A Lisp for children, with a turtle',
    blurb:
      'Designed at BBN in 1967, Logo is a Lisp dialect with far fewer parentheses, in which children define procedures and use recursion. The turtle, first a floor robot and later a cursor, made geometry something you could walk through: FORWARD 100 RIGHT 90. Papert’s 1980 book Mindstorms carried it into classrooms worldwide.',
    ideas: ['repl', 'lambda'],
    magnitude: 2,
  },
  {
    id: 'macsyma',
    name: 'Macsyma',
    kind: 'Tool',
    constellation: 'Lisp',
    year: 1968,
    people: 'Carl Engelman, William Martin, Joel Moses',
    epithet: 'Algebra by symbol manipulation',
    blurb:
      'Begun at MIT’s Project MAC in 1968, Macsyma did algebra and calculus symbolically: integrate, factor, simplify. It was one of the largest Lisp programs of its era, and its demands for big numbers and fast arithmetic shaped MacLisp. Its open-source descendant, Maxima, is still maintained.',
    ideas: ['homoiconicity'],
    magnitude: 3,
  },
  {
    id: 'scheme',
    name: 'Scheme',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1975,
    people: 'Gerald Jay Sussman, Guy L. Steele Jr.',
    epithet: 'Lisp, rebuilt on λ-calculus',
    blurb:
      'Sussman and Steele wrote Scheme in 1975 to understand Hewitt’s actors, and found their code for creating an actor was the same as their code for creating a closure. It brought ALGOL’s lexical scope to Lisp, required proper tail calls and made continuations first-class. It was meant to be “Schemer”, cut to six characters by their operating system’s filename limit.',
    ideas: ['lambda', 'continuations'],
    magnitude: 1,
  },
  {
    id: 'lisp-machines',
    name: 'Lisp Machines',
    kind: 'Tool',
    constellation: 'Lisp',
    year: 1979,
    people: 'Richard Greenblatt, Tom Knight; Symbolics, LMI',
    epithet: 'Computers whose machine code was Lisp',
    blurb:
      'MIT’s AI Lab built workstations whose hardware understood tagged Lisp data, and around 1980 its CADR design was commercialised by Symbolics and Lisp Machines Inc. Their environments let you inspect and redefine any function in the running system, the operating system included. Cheaper Unix workstations and the AI winter of the late 1980s ended them.',
    ideas: ['repl'],
    magnitude: 3,
  },
  {
    id: 'flavors',
    name: 'Flavors',
    kind: 'Language',
    constellation: 'Objects',
    year: 1979,
    people: 'Howard Cannon',
    epithet: 'Where the mixin got its name',
    blurb:
      'Howard Cannon’s object system for the MIT Lisp Machine, inspired by Smalltalk, let a class inherit from several “flavors” at once. Small add-on flavors were called mixins, after Steve’s Ice Cream in Somerville, which mixed sweets into a base flavour. Its method combination, wrapping a method with code that runs before or after it, went straight into CLOS.',
    ideas: ['objects'],
    magnitude: 3,
  },
  {
    id: 'common-lisp',
    name: 'Common Lisp',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1984,
    people:
      'Guy Steele, Scott Fahlman, Richard Gabriel, David Moon, Daniel Weinreb et al.',
    epithet: 'MacLisp’s heirs, reunited by committee',
    blurb:
      'By the early 1980s MacLisp had splintered into incompatible successors, and Steele’s Common Lisp the Language (1984) reunited them. Its condition system lets a handler pick a restart while the failing code’s stack is still alive: resumable errors decades before effect handlers. ANSI standardised the language, CLOS included, in 1994.',
    ideas: ['homoiconicity'],
    magnitude: 2,
  },
  {
    id: 'emacs-lisp',
    name: 'Emacs Lisp',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1985,
    people: 'Richard Stallman',
    epithet: 'The Lisp inside your editor',
    blurb:
      'Stallman wrote GNU Emacs in 1985 as a small C core with most of the editor in its own Lisp, a dialect modelled on MacLisp. Every keystroke runs a Lisp function you can inspect, redefine or advise while you edit. It used dynamic scope alone until Emacs 24 (2012) added lexical binding as a per-file option.',
    ideas: ['repl'],
    magnitude: 3,
  },
  {
    id: 'clos',
    name: 'CLOS',
    kind: 'Language',
    constellation: 'Objects',
    year: 1988,
    people:
      'Daniel Bobrow, Linda DeMichiel, Richard Gabriel, Sonya Keene, Gregor Kiczales, David Moon',
    epithet: 'Methods belong to functions, not classes',
    blurb:
      'The Common Lisp Object System turned methods inside out: a generic function owns its methods and chooses one by the classes of all its arguments, not just the first. :before, :after and :around methods wrap behaviour without touching it. Its metaobject protocol, written up in The Art of the Metaobject Protocol (1991), made the object system itself programmable.',
    ideas: ['dispatch', 'objects'],
    magnitude: 2,
  },
  {
    id: 'racket',
    name: 'Racket',
    kind: 'Language',
    constellation: 'Lisp',
    year: 1995,
    people:
      'Matthias Felleisen, Matthew Flatt, Robert Bruce Findler, Shriram Krishnamurthi',
    epithet: 'A language for making languages',
    blurb:
      'Racket began in 1995 as PLT Scheme, built for teaching alongside the DrScheme environment and the textbook How to Design Programs. Renamed in 2010 because it had outgrown Scheme, it starts every file with #lang, so one system hosts Typed Racket, teaching languages and a documentation language. Since 2021 it has run on Chez Scheme.',
    ideas: ['homoiconicity'],
    magnitude: 2,
  },
  {
    id: 'typed-racket',
    name: 'Typed Racket',
    kind: 'Language',
    constellation: 'Lisp',
    year: 2008,
    people: 'Sam Tobin-Hochstadt, Matthias Felleisen',
    epithet: 'Types that follow your if statements',
    blurb:
      'Typed Racket (POPL 2008, as Typed Scheme) added static types to existing untyped programs one module at a time. Its occurrence typing narrows a variable’s type after a test like (number? x), the move TypeScript users know from typeof checks. Contracts guard the boundary wherever typed code meets untyped code.',
    ideas: ['inference'],
    magnitude: 3,
  },
  {
    id: 'minikanren',
    name: 'miniKanren',
    kind: 'Language',
    constellation: 'Logic',
    year: 2005,
    people: 'Daniel Friedman, William Byrd, Oleg Kiselyov',
    epithet: 'Logic programming in a page of Scheme',
    blurb:
      'Introduced in The Reasoned Schemer (2005), miniKanren embeds relational programming in Scheme with a core small enough to read in an afternoon. Relations run in any direction: an interpreter written as a relation can run backwards, generating programs that produce a given output. Clojure’s core.logic is a port.',
    ideas: ['logic'],
    magnitude: 3,
  },
  {
    id: 'clojure',
    name: 'Clojure',
    kind: 'Language',
    constellation: 'Lisp',
    year: 2007,
    people: 'Rich Hickey',
    epithet: 'Immutable by default, on the JVM',
    blurb:
      'Hickey worked on Clojure for over two years, largely self-funded, before releasing it in 2007. It is a Lisp for the JVM whose maps and vectors are persistent tries after Phil Bagwell, so “changing” one returns a new version that shares structure with the old. Shared state goes through atoms or transactional refs; ClojureScript followed in 2011.',
    ideas: ['immutability', 'stm'],
    magnitude: 1,
  },

  // OBJECTS & MESSAGES

  {
    id: 'simula',
    name: 'Simula 67',
    kind: 'Language',
    constellation: 'Objects',
    year: 1967,
    people: 'Ole-Johan Dahl, Kristen Nygaard',
    epithet: 'Classes, born to simulate ships and queues',
    blurb:
      'Dahl and Nygaard at the Norwegian Computing Center extended ALGOL 60 to write simulations, which needed things that carried their own state and behaviour. Simula 67 introduced classes, objects, inheritance, virtual procedures and coroutines. Bjarne Stroustrup used it during his PhD at Cambridge and later carried its classes into C.',
    ideas: ['objects', 'continuations'],
    magnitude: 2,
  },
  {
    id: 'smalltalk',
    name: 'Smalltalk',
    kind: 'Language',
    constellation: 'Objects',
    year: 1972,
    people: 'Alan Kay, Dan Ingalls, Adele Goldberg',
    epithet: 'Everything is an object, even 3',
    blurb:
      'Built at Xerox PARC for Kay’s Dynabook, Smalltalk made everything an object, numbers included, and all computation a message send: even 3 + 4. Kay credits the half page of Lisp that defines eval, and Simula’s objects. The whole system, compiler and debugger included, lived in a running image you could change while it ran.',
    ideas: ['objects', 'repl'],
    magnitude: 1,
  },
  {
    id: 'self',
    name: 'Self',
    kind: 'Language',
    constellation: 'Objects',
    year: 1987,
    people: 'David Ungar, Randall Smith',
    epithet: 'Objects without classes',
    blurb:
      'Self removed classes: objects are cloned from prototypes and delegate to parent objects. Making that fast pushed its team at Stanford and Sun to invent adaptive optimisation and polymorphic inline caches. Self alumni founded Animorphic to build Strongtalk; Sun bought the company in 1997 and its VM became the basis of Java’s HotSpot. Lars Bak, who worked on Self, later led Chrome’s V8.',
    ideas: ['objects'],
    magnitude: 3,
  },
  {
    id: 'python',
    name: 'Python',
    kind: 'Language',
    constellation: 'Objects',
    year: 1991,
    people: 'Guido van Rossum',
    epithet: 'Readable, and quietly functional',
    blurb:
      'Van Rossum released Python in 1991. Lambda, map, filter and reduce arrived in 1994 as a patch from a Lisp fan, and list comprehensions were borrowed from Haskell in 2000. Generators (2001), Dylan’s C3 method order (2003), async/await (2015) and pattern matching (2021) followed: the notebook language is a slow accumulation of FP ideas.',
    ideas: ['comprehensions'],
    magnitude: 1,
  },
  {
    id: 'dylan',
    name: 'Dylan',
    kind: 'Language',
    constellation: 'Objects',
    year: 1992,
    people: 'Apple Cambridge Research Lab (David Moon, Andrew Shalit et al.)',
    epithet: 'CLOS in ALGOL’s clothes',
    blurb:
      'Apple’s Cambridge lab designed Dylan, short for “dynamic language”, as CLOS-style semantics for small machines like the Newton. The 1992 manual used Lisp syntax; a later revision switched to infix. Apple dropped it, but its 1996 paper on a monotonic superclass linearization, C3, gave Python, Raku and Solidity their method resolution order.',
    ideas: ['dispatch'],
    magnitude: 3,
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    kind: 'Language',
    constellation: 'Objects',
    year: 1995,
    people: 'Brendan Eich',
    epithet: 'Scheme in the browser, dressed as Java',
    blurb:
      'Netscape recruited Eich in 1995 with the promise of putting Scheme in the browser; management then wanted it to look like Java, and he built the first version in ten days. Under the braces are Scheme-style first-class functions, which became full closures when nested functions arrived in 1997, and prototypes inspired by Self. That accident put closures in front of more programmers than any language before it.',
    ideas: ['lambda'],
    magnitude: 1,
  },
  {
    id: 'ruby',
    name: 'Ruby',
    kind: 'Language',
    constellation: 'Objects',
    year: 1995,
    people: 'Yukihiro “Matz” Matsumoto',
    epithet: 'A Lisp with Smalltalk’s objects',
    blurb:
      'Matz released Ruby in Japan in 1995. He has described it as a simple Lisp, minus macros and S-expressions, plus a simple object system, blocks inspired by higher-order functions, methods from Smalltalk and Perl’s practicality. Blocks made map and each everyday Ruby, and modules mixed into classes became its answer to multiple inheritance.',
    ideas: ['lambda', 'objects'],
    magnitude: 2,
  },
  {
    id: 'java',
    name: 'Java',
    kind: 'Language',
    constellation: 'Objects',
    year: 1995,
    people: 'James Gosling, Sun Microsystems',
    epithet: 'Garbage collection goes mainstream',
    blurb:
      'Java made garbage collection and a virtual machine normal for business software. Its generics (2004) came from Odersky and Wadler’s GJ, lambdas and streams arrived in Java 8 (2014), and Java 21 (2023) finalised pattern-matching switch, record patterns and virtual threads. Guy Steele, co-creator of Scheme, co-wrote its language specification.',
    ideas: ['gc'],
    magnitude: 1,
  },
  {
    id: 'pizza',
    name: 'Pizza',
    kind: 'Language',
    constellation: 'Objects',
    year: 1996,
    people: 'Martin Odersky, Philip Wadler',
    epithet: 'Java with generics, closures and pattern matching',
    blurb:
      'Pizza (POPL 1997) compiled to ordinary Java bytecode but added parametric polymorphism, first-class functions and algebraic data types. Generics were the part Sun wanted, so Odersky and Wadler, with Gilad Bracha and David Stoutamire, built GJ, which became Java 5’s generics. Odersky’s GJ compiler became the standard javac.',
    ideas: ['adts', 'lambda'],
    magnitude: 3,
  },
  {
    id: 'csharp',
    name: 'C#',
    kind: 'Language',
    constellation: 'Objects',
    year: 2000,
    people: 'Anders Hejlsberg',
    epithet: 'The OO language that kept importing FP',
    blurb:
      'Microsoft announced C# in 2000. Its generics (2005) were built into the .NET runtime by Andrew Kennedy and Don Syme of Microsoft Research Cambridge, not erased as in Java. LINQ (2007) brought query comprehensions and C# 5 (2012) brought async/await. Hejlsberg had earlier created Turbo Pascal and Delphi, and went on to lead TypeScript.',
    ideas: ['objects'],
    magnitude: 2,
  },
  {
    id: 'aspectj',
    name: 'AspectJ',
    kind: 'Tool',
    constellation: 'Objects',
    year: 2001,
    people: 'Gregor Kiczales and the Xerox PARC team',
    epithet: 'Method combination, cut loose from CLOS',
    blurb:
      'Kiczales, a CLOS designer and co-author of The Art of the Metaobject Protocol, led the Xerox PARC group that named aspect-oriented programming in 1997. AspectJ extended Java with before, after and around advice that can wrap many methods at once: CLOS’s method combination, generalised. Spring’s AOP uses its pointcut language.',
    ideas: ['dispatch'],
    magnitude: 3,
  },
  {
    id: 'linq',
    name: 'LINQ',
    kind: 'Tool',
    constellation: 'Objects',
    year: 2007,
    people: 'Erik Meijer, Anders Hejlsberg',
    epithet: 'Monad comprehensions in C#',
    blurb:
      'Language Integrated Query, in C# 3.0 (2007), lets you write from x in xs where … select … over lists, XML or SQL databases. Under the syntax it calls SelectMany, which is monadic bind, so it works for anything with the right methods. C# 3 gained lambdas, var and extension methods largely to make LINQ possible.',
    ideas: ['comprehensions', 'monads', 'hof'],
    magnitude: 2,
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    kind: 'Language',
    constellation: 'Objects',
    year: 2011,
    people: 'Andrey Breslav, JetBrains',
    epithet: 'Null safety on the JVM',
    blurb:
      'JetBrains announced Kotlin in 2011, naming it after an island near St Petersburg. It puts nullability in the type (String versus String?), adds data and sealed classes, and has coroutines whose structured concurrency ties every child task to a scope. Google made it the preferred language for Android in 2019.',
    ideas: ['optionresult', 'fibers'],
    magnitude: 2,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    kind: 'Language',
    constellation: 'Objects',
    year: 2012,
    people: 'Anders Hejlsberg',
    epithet: 'Types for the JavaScript you already have',
    blurb:
      'TypeScript (2012) types JavaScript structurally, by shape rather than name. Version 2.0 (2016) brought discriminated unions and control-flow narrowing, and 2.8 (2018) conditional types, which turned its type system into a small functional language. Its compiler has been ported to Go as TypeScript 7, and that port checks this page.',
    ideas: ['adts', 'inference'],
    magnitude: 1,
  },

  // IMPERATIVE & SYSTEMS

  {
    id: 'fortran',
    name: 'Fortran',
    kind: 'Language',
    constellation: 'Imperative',
    year: 1957,
    people: 'John Backus and an IBM team',
    epithet: 'The first compiler people trusted',
    blurb:
      'Backus’s IBM team shipped Fortran for the IBM 704 in 1957, proving a compiler could produce code nearly as fast as hand-written assembly. McCarthy’s first list-processing experiments were in FLPL, a Fortran extension. Twenty years later Backus used his Turing lecture to argue against the word-at-a-time style Fortran had established.',
    ideas: ['arrays'],
    magnitude: 2,
  },
  {
    id: 'algol',
    name: 'ALGOL 60',
    kind: 'Language',
    constellation: 'Imperative',
    year: 1960,
    people:
      'Peter Naur (editor), John Backus, John McCarthy, Alan Perlis et al.',
    epithet: 'Block structure, scope and BNF',
    blurb:
      'An international committee’s report gave ALGOL 60 nested blocks, lexical scope, recursive procedures and a grammar written in BNF. McCarthy, a member, brought conditional expressions from his Lisp work. Its call-by-name parameters, re-evaluated at every use, foreshadowed lazy evaluation. Tony Hoare later called it an improvement on nearly all its successors.',
    ideas: [],
    magnitude: 1,
  },
  {
    id: 'c',
    name: 'C',
    kind: 'Language',
    constellation: 'Imperative',
    year: 1972,
    people: 'Dennis Ritchie, Ken Thompson',
    epithet: 'Portable assembly that rewrote Unix',
    blurb:
      'Ritchie developed C at Bell Labs around 1972 from Thompson’s B, which came from Martin Richards’s BCPL, a descendant of ALGOL by way of CPL. Unix was rewritten in it in 1973. Its braces and semicolons became the default look of Java, JavaScript, C# and Go, whatever their semantics.',
    ideas: [],
    magnitude: 2,
  },
  {
    id: 'cpp',
    name: 'C++',
    kind: 'Language',
    constellation: 'Imperative',
    year: 1985,
    people: 'Bjarne Stroustrup',
    epithet: 'Simula’s classes at C’s speed',
    blurb:
      'Stroustrup started “C with Classes” in 1979 to get Simula’s organisation without its slowness; C++ shipped commercially in 1985. Destructors gave it RAII, tying resources to scope. Templates turned out to be a compile-time functional language, and C++11 added lambdas, C++17 std::optional and std::variant.',
    ideas: ['ownership'],
    magnitude: 2,
  },
  {
    id: 'cyclone',
    name: 'Cyclone',
    kind: 'Language',
    constellation: 'Imperative',
    year: 2002,
    people:
      'Trevor Jim, Greg Morrisett, Dan Grossman, Michael Hicks, James Cheney, Yanling Wang',
    epithet: 'Safe C, with regions',
    blurb:
      'Cyclone, from AT&T Labs and Cornell (2002), kept C’s syntax and control over memory while ruling out dangling pointers and buffer overruns. Pointers carry region annotations, so the compiler knows how long the memory they point into lives; ML-style tagged unions and pattern matching came too. The Rust Reference lists it as an influence.',
    ideas: ['ownership'],
    magnitude: 3,
  },
  {
    id: 'go',
    name: 'Go',
    kind: 'Language',
    constellation: 'Imperative',
    year: 2009,
    people: 'Robert Griesemer, Rob Pike, Ken Thompson',
    epithet: 'CSP for the data centre',
    blurb:
      'Designed at Google from 2007 and released in 2009, Go is deliberately small: C-like syntax, garbage collection, fast builds. Its goroutines and channels come, as its FAQ says, from Hoare’s CSP, by way of Newsqueak and Limbo, earlier Bell Labs languages Pike worked on. Generics waited until Go 1.18 in 2022.',
    ideas: ['fibers'],
    magnitude: 2,
  },
  {
    id: 'rust',
    name: 'Rust',
    kind: 'Language',
    constellation: 'Imperative',
    year: 2010,
    people: 'Graydon Hoare, Mozilla',
    epithet: 'ML’s types with C++’s control',
    blurb:
      'Hoare began Rust as a side project in 2006 and Mozilla announced it in 2010; its first compiler was written in OCaml. It brought ML’s enums, match and type inference to systems programming, with traits after Haskell’s type classes and an ownership system that frees memory without a garbage collector. Its 2016 redesign of error messages was inspired by Elm.',
    ideas: ['ownership', 'optionresult'],
    magnitude: 1,
  },
  {
    id: 'swift',
    name: 'Swift',
    kind: 'Language',
    constellation: 'Imperative',
    year: 2014,
    people: 'Chris Lattner, Apple',
    epithet: 'Optionals and enums for Apple’s platforms',
    blurb:
      'Lattner started Swift in 2010 and Apple unveiled it in 2014. His own list of its influences names Objective-C, Rust, Haskell, Ruby, Python, C# and CLU. Optionals, enums with payloads, pattern matching and protocols with associated types made FP ideas everyday iPhone code, and Swift 5.5 (2021) added async/await and actors.',
    ideas: ['optionresult', 'adts'],
    magnitude: 1,
  },

  // THE ML FAMILY

  {
    id: 'iswim',
    name: 'ISWIM',
    kind: 'Language',
    constellation: 'Ml',
    year: 1966,
    people: 'Peter Landin',
    epithet: 'The next 700 languages, sketched in one',
    blurb:
      'Landin’s 1966 paper “The Next 700 Programming Languages” described ISWIM, “If you See What I Mean”: λ-calculus with let, where and syntactic sugar, a phrase Landin coined. It was never implemented as written. Its off-side rule became Haskell’s indentation-sensitive layout, and his SECD machine (1964) showed how to evaluate such code mechanically.',
    ideas: ['lambda'],
    magnitude: 2,
  },
  {
    id: 'lcf',
    name: 'LCF',
    kind: 'Tool',
    constellation: 'Proof',
    year: 1972,
    people: 'Robin Milner',
    epithet: 'Where ML was born',
    blurb:
      'LCF, Logic for Computable Functions, was Milner’s interactive theorem prover, begun at Stanford in 1972 and continued at Edinburgh. To script its proofs he created ML, the “meta language”. The LCF approach makes theorem an abstract type whose only constructors are the inference rules, so the type checker guarantees every theorem was properly derived.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'ml',
    name: 'ML',
    kind: 'Language',
    constellation: 'Ml',
    year: 1973,
    people: 'Robin Milner, Michael Gordon, Christopher Wadsworth et al.',
    epithet: 'Types you never have to write down',
    blurb:
      'ML began in Edinburgh around 1973 as the meta language for scripting LCF proofs. It combined Hindley–Milner type inference with exceptions and mutable references, so programs were type-safe without annotations. Algebraic data types and pattern matching arrived from Hope, and the family split into Standard ML, Caml and later OCaml and F#.',
    ideas: ['inference'],
    magnitude: 1,
  },
  {
    id: 'hope',
    name: 'Hope',
    kind: 'Language',
    constellation: 'Ml',
    year: 1980,
    people: 'Rod Burstall, David MacQueen, Don Sannella',
    epithet: 'Where data types met pattern matching',
    blurb:
      'Hope, from Edinburgh in 1980, joined user-defined data types and pattern-matching equations, which Burstall had developed in NPL, to ML’s polymorphic types. That pairing passed from Hope into Standard ML and Haskell, and from them into Rust enums, Swift enums and the discriminated unions of TypeScript.',
    ideas: ['adts'],
    magnitude: 3,
  },
  {
    id: 'sml',
    name: 'Standard ML',
    kind: 'Language',
    constellation: 'Ml',
    year: 1983,
    people: 'Robin Milner, Mads Tofte, Robert Harper, David MacQueen',
    epithet: 'A language with a mathematical definition',
    blurb:
      'Standard ML, begun in 1983, merged ML, Hope and Luca Cardelli’s ML dialect. The Definition of Standard ML (1990) specified the whole language formally, so its type safety could be proved rather than hoped for. MacQueen’s modules and functors, functions from modules to modules, remain among the most expressive module systems around.',
    ideas: ['adts', 'inference'],
    magnitude: 2,
  },
  {
    id: 'caml',
    name: 'Caml',
    kind: 'Language',
    constellation: 'Ml',
    year: 1985,
    people: 'Gérard Huet, Guy Cousineau, Ascánder Suárez, Pierre Weis',
    epithet: 'ML, French style',
    blurb:
      'INRIA’s Formel team built Caml from 1985 as their own ML, partly to implement the Coq prover. The name came from the Categorical Abstract Machine, an execution model derived from category theory by Cousineau, Curien and Mauny. Xavier Leroy and Damien Doligez’s Caml Light (1990) was small and fast enough for teaching, and led to OCaml.',
    ideas: ['inference'],
    magnitude: 3,
  },
  {
    id: 'cml',
    name: 'Concurrent ML',
    kind: 'Language',
    constellation: 'Ml',
    year: 1991,
    people: 'John Reppy',
    epithet: 'Communication as first-class values',
    blurb:
      'Reppy’s Concurrent ML (PLDI 1991) added threads and synchronous channels to Standard ML, but its key idea was the event: a value describing a possible communication, which you can combine and choose between before you synchronise on it. OCaml’s Event module and Racket’s synchronizable events follow its design.',
    ideas: ['fibers'],
    magnitude: 3,
  },
  {
    id: 'ocaml',
    name: 'OCaml',
    kind: 'Language',
    constellation: 'Ml',
    year: 1996,
    people: 'Xavier Leroy, Jérôme Vouillon, Damien Doligez, Didier Rémy',
    epithet: 'The pragmatic ML',
    blurb:
      'Objective Caml (1996) added objects to Caml, using Rémy and Vouillon’s row polymorphism so objects are typed by structure and inferred. Fast native code made it a favourite for building other languages: Rust’s first compiler, Facebook’s Flow and Hack checkers, and Rocq were written in it. Jane Street runs a trading firm on it.',
    ideas: ['inference', 'adts'],
    magnitude: 1,
  },
  {
    id: 'scala',
    name: 'Scala',
    kind: 'Language',
    constellation: 'Ml',
    year: 2004,
    people: 'Martin Odersky',
    epithet: 'Objects and functions, fused on the JVM',
    blurb:
      'After Pizza and GJ, Odersky designed Scala at EPFL, released in 2004, to show that objects and functions can be one thing. Traits, case classes with pattern matching, for-comprehensions and implicits used as type classes made it the JVM’s home for FP. Scalaz, Cats, Akka, Spark and ZIO all grew up in it.',
    ideas: ['adts', 'typeclasses', 'comprehensions'],
    magnitude: 1,
  },
  {
    id: 'fsharp',
    name: 'F#',
    kind: 'Language',
    constellation: 'Ml',
    year: 2005,
    people: 'Don Syme',
    epithet: 'OCaml for .NET, and the |> pipe',
    blurb:
      'Syme, who had co-designed .NET generics, built F# at Microsoft Research Cambridge as an OCaml for .NET, first released in 2005. It made the |> pipe famous; Syme traced the operator back to Isabelle’s ML code of 1994. F#’s async workflows (2007), one use of its computation expressions, led directly to C#’s async/await.',
    ideas: ['pipelines', 'monads'],
    magnitude: 2,
  },
  {
    id: 'ocaml5',
    name: 'OCaml 5',
    kind: 'Language',
    constellation: 'Effects',
    year: 2022,
    people:
      'KC Sivaramakrishnan, Stephen Dolan, Leo White, Anil Madhavapeddy et al.',
    epithet: 'Effect handlers in an industrial runtime',
    blurb:
      'After years of Multicore OCaml research, OCaml 5.0 (December 2022) shipped shared-memory parallelism and effect handlers. Handlers let a library suspend a computation and resume it later without monads, so the Eio library offers direct-style async I/O in which code needs no async keyword or wrapped return type.',
    ideas: ['effects'],
    magnitude: 2,
  },
  {
    id: 'reason',
    name: 'ReasonML',
    kind: 'Language',
    constellation: 'Reactive',
    year: 2016,
    people: 'Jordan Walke',
    epithet: 'OCaml with a JavaScript accent',
    blurb:
      'Walke, who created React, released Reason at Facebook in 2016: OCaml’s semantics and type system behind a JavaScript-like syntax. Reason’s own documentation notes that React’s first prototypes were written in Standard ML. By 2017 half of Messenger.com’s web code had been converted to it, and its compiler lineage continues as ReScript.',
    ideas: ['adts'],
    magnitude: 3,
  },

  // PROOFS & DEPENDENT TYPES

  {
    id: 'automath',
    name: 'Automath',
    kind: 'Language',
    constellation: 'Proof',
    year: 1967,
    people: 'Nicolaas Govert de Bruijn',
    epithet: 'The first machine-checked mathematics',
    blurb:
      'De Bruijn started Automath at Eindhoven in 1967 to check mathematics by computer, writing proofs as terms of a typed λ-calculus: Curry–Howard in practice. In 1977 Bert Jutting checked all of Landau’s Foundations of Analysis in it. De Bruijn indices, his nameless notation for bound variables, are still used inside compilers and proof assistants.',
    ideas: ['proofs'],
    magnitude: 3,
  },
  {
    id: 'isabelle',
    name: 'Isabelle',
    kind: 'Tool',
    constellation: 'Proof',
    year: 1986,
    people: 'Lawrence Paulson, Tobias Nipkow, Makarius Wenzel',
    epithet: 'A generic prover in the LCF tradition',
    blurb:
      'Paulson’s Isabelle (1986) is a framework in which many logics can be encoded; higher-order logic, Isabelle/HOL, is the most used. Written in Standard ML in the LCF style, it was used to verify the seL4 microkernel. Its ML sources are also where, by Don Syme’s account, the |> operator first appeared.',
    ideas: ['proofs', 'pipelines'],
    magnitude: 3,
  },
  {
    id: 'coq',
    name: 'Rocq (Coq)',
    kind: 'Language',
    constellation: 'Proof',
    year: 1989,
    people: 'Thierry Coquand, Gérard Huet, Christine Paulin-Mohring',
    epithet: 'Proofs and programs in one language',
    blurb:
      'Coquand and Huet’s Calculus of Constructions (1984–85) became the Coq prover, first released in 1989 and implemented in Caml. It was used to check the four colour theorem (Gonthier, 2005) and to build CompCert, a C compiler proved to preserve the meaning of programs. In 2025 it was renamed Rocq.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'agda',
    name: 'Agda',
    kind: 'Language',
    constellation: 'Proof',
    year: 1999,
    people: 'Catarina Coquand; Ulf Norell',
    epithet: 'Dependently typed, and fluent in Unicode',
    blurb:
      'The first Agda came from Chalmers in 1999; Ulf Norell’s 2007 rewrite, Agda 2, is the one in use, and it is implemented in Haskell. You prove things by writing programs, filling typed holes interactively in the editor. Mixfix operators and Unicode let definitions look like mathematics: if_then_else_ is an ordinary name.',
    ideas: ['proofs'],
    magnitude: 2,
  },
  {
    id: 'idris',
    name: 'Idris',
    kind: 'Language',
    constellation: 'Proof',
    year: 2007,
    people: 'Edwin Brady',
    epithet: 'Dependent types for everyday programs',
    blurb:
      'Brady designed Idris at St Andrews to make dependent types practical for ordinary programs, not just proofs. Its syntax is deliberately close to Haskell, and Idris 1 was implemented in Haskell. Idris 2 (2020) is written in Idris, compiles via Chez Scheme by default, and uses quantitative types to track how many times a value is used.',
    ideas: ['proofs', 'ownership'],
    magnitude: 2,
  },
  {
    id: 'lean',
    name: 'Lean',
    kind: 'Language',
    constellation: 'Proof',
    year: 2013,
    people: 'Leonardo de Moura, Sebastian Ullrich',
    epithet: 'Proof assistant and programming language',
    blurb:
      'De Moura started Lean at Microsoft Research in 2013. Lean 4 (2021) is also a general-purpose functional language, written mostly in itself, with Haskell-style do-notation and type classes. Its community library, Mathlib, covers much of undergraduate mathematics, and Lean is the language AlphaProof writes its proofs in.',
    ideas: ['proofs'],
    magnitude: 1,
  },
  {
    id: 'alphaproof',
    name: 'AlphaProof',
    kind: 'Tool',
    constellation: 'Proof',
    year: 2024,
    people: 'Google DeepMind',
    epithet: 'Learned search, checked by Lean',
    blurb:
      'At the 2024 International Mathematical Olympiad, DeepMind’s AlphaProof and AlphaGeometry 2 together solved four of the six problems, a silver-medal standard. AlphaProof trained itself, AlphaZero-style, on millions of problems translated into Lean, so every solution it found was a machine-checked proof. Symbolic AI’s 1956 dream, steered by a neural network.',
    ideas: ['proofs'],
    magnitude: 2,
  },

  // LAZY & PURE

  {
    id: 'sasl',
    name: 'SASL',
    kind: 'Language',
    constellation: 'Lazy',
    year: 1972,
    people: 'David Turner',
    epithet: 'Small, pure, and eventually lazy',
    blurb:
      'Turner wrote the St Andrews Static Language in 1972 as a purely applicative subset of ISWIM for teaching. The 1976 version was lazy, and in 1979 he implemented it by compiling to S and K combinators and reducing the resulting graph, a technique that shaped lazy-language implementations for a decade. SASL led to KRC and Miranda.',
    ideas: ['laziness'],
    magnitude: 3,
  },
  {
    id: 'miranda',
    name: 'Miranda',
    kind: 'Language',
    constellation: 'Lazy',
    year: 1985,
    people: 'David Turner',
    epithet: 'Lazy, pure, typed, and trademarked',
    blurb:
      'Turner’s Miranda (1985) combined lazy evaluation, Hindley–Milner types, algebraic data types and list comprehensions in a tidy, indentation-sensitive syntax. It was a commercial product of Research Software Ltd. When researchers met at FPCA 1987 to unify the many lazy languages, they asked to start from Miranda; Turner, wanting one standard rather than many dialects, declined, so they designed a new, freely available language: Haskell.',
    ideas: ['laziness', 'comprehensions'],
    magnitude: 2,
  },
  {
    id: 'clean',
    name: 'Clean',
    kind: 'Language',
    constellation: 'Lazy',
    year: 1987,
    people: 'Rinus Plasmeijer, Marko van Eekelen',
    epithet: 'Purity with uniqueness types',
    blurb:
      'Clean, from Radboud University Nijmegen (1987), is a lazy pure language close to Haskell. Instead of monads it handles I/O with uniqueness types: if the type system knows a value, such as the world or a file, has exactly one reference, it can be updated in place without breaking purity. It is an early relative of ownership typing.',
    ideas: ['ownership', 'purity'],
    magnitude: 3,
  },
  {
    id: 'haskell',
    name: 'Haskell',
    kind: 'Language',
    constellation: 'Lazy',
    year: 1990,
    people: 'Paul Hudak, Philip Wadler, Simon Peyton Jones, John Hughes et al.',
    epithet: 'Lazy, pure, and named after Haskell Curry',
    blurb:
      'A committee formed at FPCA 1987 to unify a dozen lazy languages, and Haskell 1.0 arrived in 1990. Purity made I/O awkward until Haskell 1.3 (1996) settled on monadic IO with do-notation. Type classes, monads, QuickCheck and STM all reached the mainstream through it, and GHC is still where many new ideas are tried first.',
    ideas: ['laziness', 'purity', 'typeclasses', 'monads'],
    magnitude: 1,
  },
  {
    id: 'quickcheck',
    name: 'QuickCheck',
    kind: 'Tool',
    constellation: 'Lazy',
    year: 2000,
    people: 'Koen Claessen, John Hughes',
    epithet: 'Tests that write themselves',
    blurb:
      'Claessen and Hughes’s ICFP 2000 paper: state a property, such as “reversing a list twice gives it back”, and the library generates random inputs to try to refute it; later versions shrink a failure to a minimal case. Hughes co-founded Quviq to apply it to Erlang. Hypothesis, fast-check and proptest descend from it.',
    ideas: ['testing'],
    magnitude: 2,
  },
  {
    id: 'nix',
    name: 'Nix',
    kind: 'Tool',
    constellation: 'Lazy',
    year: 2003,
    people: 'Eelco Dolstra',
    epithet: 'Package builds as pure functions',
    blurb:
      'Dolstra began Nix at Utrecht in 2003 and described it in his 2006 thesis. A package is the output of a pure function of its inputs, stored in /nix/store under a hash of them, so builds are reproducible and versions coexist. The Nix language is lazy, which lets nixpkgs describe over 100,000 packages without evaluating them all.',
    ideas: ['purity', 'laziness'],
    magnitude: 2,
  },
  {
    id: 'purescript',
    name: 'PureScript',
    kind: 'Language',
    constellation: 'Lazy',
    year: 2013,
    people: 'Phil Freeman',
    epithet: 'Haskell, strictly, for JavaScript',
    blurb:
      'Freeman released PureScript in 2013: a Haskell-like language that compiles to readable JavaScript, evaluates strictly and needs almost no runtime. Row types describe JavaScript records precisely, and its type-class hierarchy is finer-grained than Haskell’s. It showed that full-strength typed FP could target the browser.',
    ideas: ['typeclasses'],
    magnitude: 3,
  },

  // EFFECT SYSTEMS

  {
    id: 'eff',
    name: 'Eff',
    kind: 'Language',
    constellation: 'Effects',
    year: 2012,
    people: 'Andrej Bauer, Matija Pretnar',
    epithet: 'A language built around handlers',
    blurb:
      'Bauer and Pretnar created Eff (2012) as a language in which algebraic effects and handlers are the main control mechanism, so exceptions, state, nondeterminism and I/O are all definable by users. Their paper “Programming with algebraic effects and handlers” became a standard introduction for language designers.',
    ideas: ['effects'],
    magnitude: 3,
  },
  {
    id: 'koka',
    name: 'Koka',
    kind: 'Language',
    constellation: 'Effects',
    year: 2012,
    people: 'Daan Leijen',
    epithet: 'Every function’s effects in its type',
    blurb:
      'Leijen’s Koka, from Microsoft Research, infers each function’s effects, such as exceptions, divergence or I/O, as a row in its type, and handlers discharge them. Its Perceus reference counting (2021) reuses memory in place when a value is uniquely owned. Leijen had earlier co-written Haskell’s Parsec parser library.',
    ideas: ['effects'],
    magnitude: 3,
  },
  {
    id: 'scalaz',
    name: 'Scalaz',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2008,
    people: 'Tony Morris, Rúnar Bjarnason, Jason Zaugg et al.',
    epithet: 'Haskell’s type classes, ported to Scala',
    blurb:
      'Scalaz (from 2008) brought Haskell’s Functor, Applicative, Monad and friends to Scala, with implicits supplying instances. It was dense and divisive, and a community split produced Typelevel’s Cats in 2015. John De Goes’s work on the IO type for Scalaz 8 became ZIO.',
    ideas: ['typeclasses', 'monads'],
    magnitude: 3,
  },
  {
    id: 'cats-effect',
    name: 'Cats Effect',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2017,
    people: 'Daniel Spiewak and Typelevel',
    epithet: 'IO as a standard for Scala libraries',
    blurb:
      'Cats Effect (2017) defined an IO type and a hierarchy of type classes, such as Sync and Async, so libraries like http4s, fs2 and Doobie could run on any compatible effect type. Version 3 (2021) rebuilt the runtime around fibers on a work-stealing scheduler.',
    ideas: ['monads', 'fibers'],
    magnitude: 2,
  },
  {
    id: 'zio',
    name: 'ZIO',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2018,
    people: 'John De Goes',
    epithet: 'ZIO[R, E, A]: environment, error, answer',
    blurb:
      'ZIO began in 2017 as the IO type for Scalaz 8 and became an independent library in 2018. Its three type parameters say what an effect needs, how it can fail and what it returns. Fibers, interruption, STM, resource safety and layers for dependency injection come in the box; ZIO 1.0 arrived in 2020.',
    ideas: ['fibers', 'optionresult', 'supervision'],
    magnitude: 1,
  },
  {
    id: 'fp-ts',
    name: 'fp-ts',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2017,
    people: 'Giulio Canti',
    epithet: 'Haskell’s type classes, encoded in TypeScript',
    blurb:
      'TypeScript has no higher-kinded types, so Canti’s fp-ts (2017) simulated them with an encoding from the paper “Lightweight higher-kinded polymorphism”, then built Option, Either, Task and the Functor-to-Monad hierarchy on top. His io-ts checked data at runtime against static types. Canti later joined Effect, which fp-ts now points to as its successor.',
    ideas: ['typeclasses', 'optionresult'],
    magnitude: 2,
  },
  {
    id: 'unison',
    name: 'Unison',
    kind: 'Language',
    constellation: 'Effects',
    year: 2019,
    people: 'Paul Chiusano, Rúnar Bjarnason, Arya Irani',
    epithet: 'Code addressed by its hash',
    blurb:
      'Unison identifies every definition by a hash of its syntax tree, so renaming is free, dependencies never conflict, and code can be shipped to another machine and run there. Effects are “abilities”, Unison’s name for algebraic effects, written in a function’s type and handled by its caller. Its first public alpha came in 2019.',
    ideas: ['effects'],
    magnitude: 3,
  },
  {
    id: 'effect',
    name: 'Effect',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2019,
    people: 'Michael Arnaldi, Mattia Manzati, Giulio Canti, Tim Smart et al.',
    epithet: 'ZIO’s ideas, native to TypeScript',
    blurb:
      'Arnaldi began Effect by bringing ZIO’s model to TypeScript: Effect<A, E, R> tracks the success value, typed errors and required services. Effect.gen uses generators and yield* as do-notation, so effectful code reads top to bottom. Version 3.0 was declared stable in 2024; this page is built on Effect 4.',
    ideas: ['monads', 'fibers', 'optionresult', 'pipelines'],
    magnitude: 1,
  },
  {
    id: 'async-await',
    name: 'async/await',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2012,
    people:
      'Anders Hejlsberg, Mads Torgersen and the C# team, after Don Syme’s F# async',
    epithet: 'Monadic code that looks like ordinary code',
    blurb:
      'C# 5 (2012) let a method marked async await a Task, while the compiler rewrote the rest of the method into a state machine. The design followed F#’s async workflows, a computation expression, which is to say a monad. It spread quickly: Python 3.5 in 2015, JavaScript in ES2017, Rust in 2019 and Swift in 2021.',
    ideas: ['continuations', 'monads'],
    magnitude: 2,
  },

  // REACTIVE & DATAFLOW

  {
    id: 'lucid',
    name: 'Lucid',
    kind: 'Language',
    constellation: 'Reactive',
    year: 1976,
    people: 'William Wadge, Edward Ashcroft',
    epithet: 'Every variable is a stream',
    blurb:
      'Ashcroft and Wadge introduced Lucid in 1976 as a formal system for writing and proving programs. A variable denotes the whole infinite history of its values, and operators like fby (“followed by”) define each value from earlier ones, so a loop becomes an equation. That dataflow reading inspired Lustre.',
    ideas: ['frp'],
    magnitude: 3,
  },
  {
    id: 'visicalc',
    name: 'VisiCalc',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 1979,
    people: 'Dan Bricklin, Bob Frankston',
    epithet: 'The spreadsheet: dataflow for everyone',
    blurb:
      'VisiCalc (1979) for the Apple II was the first spreadsheet for personal computers: change one cell and every formula that depends on it recalculates. People bought Apple IIs just to run it. Spreadsheets have been the most widely used reactive, functional programming environment ever since, even if their users never call it programming.',
    ideas: ['frp', 'purity'],
    magnitude: 2,
  },
  {
    id: 'esterel',
    name: 'Esterel',
    kind: 'Language',
    constellation: 'Reactive',
    year: 1983,
    people: 'Gérard Berry',
    epithet: 'Reactions that take no time',
    blurb:
      'Berry’s Esterel, begun in the early 1980s at the École des Mines and INRIA, is an imperative synchronous language: a program reacts to input signals in discrete instants, and each reaction is treated as instantaneous. That makes timing deterministic and analysable, which suits controllers and hardware. Esterel Technologies, founded to sell it, later took over SCADE.',
    ideas: ['frp'],
    magnitude: 3,
  },
  {
    id: 'lustre',
    name: 'Lustre',
    kind: 'Language',
    constellation: 'Reactive',
    year: 1984,
    people: 'Paul Caspi, Nicolas Halbwachs',
    epithet: 'Lucid’s streams, made real-time',
    blurb:
      'Caspi and Halbwachs designed Lustre at Grenoble in the mid-1980s as a synchronous dataflow language derived from Lucid: every variable is a stream with one value per clock tick. Programs read like the block diagrams control engineers already drew. Its industrial form, SCADE, generates qualified code for Airbus flight controls and railway systems.',
    ideas: ['frp'],
    magnitude: 3,
  },
  {
    id: 'rx',
    name: 'Reactive Extensions',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2009,
    people: 'Erik Meijer and team at Microsoft',
    epithet: 'LINQ, turned inside out',
    blurb:
      'Meijer’s group observed that IObservable is the mathematical dual of IEnumerable: instead of pulling values, you are pushed them. Rx (2009) gave events and asynchronous streams the whole LINQ vocabulary of map, filter and merge. Netflix’s RxJava and RxJS took it everywhere, and Angular is built on RxJS.',
    ideas: ['frp', 'hof'],
    magnitude: 2,
  },
  {
    id: 'elm',
    name: 'Elm',
    kind: 'Language',
    constellation: 'Reactive',
    year: 2012,
    people: 'Evan Czaplicki',
    epithet: 'No runtime exceptions, and friendly errors',
    blurb:
      'Czaplicki created Elm for his 2012 Harvard senior thesis, as functional reactive programming for GUIs. In 0.17 (2016), announced as “A Farewell to FRP”, he dropped signals for The Elm Architecture: model, update, view, plus subscriptions. Its compiler errors, written as helpful sentences, inspired Rust’s 2016 redesign of its own.',
    ideas: ['tea', 'frp', 'purity'],
    magnitude: 1,
  },
  {
    id: 'react',
    name: 'React',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2013,
    people: 'Jordan Walke, Facebook',
    epithet: 'UI as a function of state',
    blurb:
      'Walke built React at Facebook, and it was open-sourced in 2013: describe the UI for the current state and React works out the DOM changes. Re-rendering everything and diffing horrified people at first. Walke’s earliest prototypes were written in Standard ML, and React taught a generation of front-end developers to write pure render functions.',
    ideas: ['purity', 'tea'],
    magnitude: 1,
  },
  {
    id: 'immutable-js',
    name: 'Immutable.js',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2014,
    people: 'Lee Byron, Facebook',
    epithet: 'Clojure’s collections for JavaScript',
    blurb:
      'Byron’s Immutable.js (2014) gave JavaScript persistent List and Map types built from hash-map and vector tries, structures its README describes as popularised by Clojure and Scala. Because unchanged data keeps its identity, a React app could skip re-rendering a subtree with a single reference check.',
    ideas: ['immutability'],
    magnitude: 3,
  },
  {
    id: 'redux',
    name: 'Redux',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2015,
    people: 'Dan Abramov, Andrew Clark',
    epithet: 'The Elm Architecture, for React',
    blurb:
      'Abramov wrote Redux in 2015 for a conference talk on hot reloading and time-travel debugging. State lives in one store and changes only through reducers, pure functions from state and action to the next state. Its documentation credits Flux and Elm as prior art, and a reducer is essentially Elm’s update with the arguments swapped.',
    ideas: ['tea', 'purity', 'immutability'],
    magnitude: 2,
  },
  {
    id: 'react-hooks',
    name: 'React Hooks',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2018,
    people:
      'Sebastian Markbåge, Andrew Clark, Dan Abramov, Sophie Alpert et al.',
    epithet: 'State and effects inside plain functions',
    blurb:
      'Announced in 2018 and released in React 16.8 (2019), hooks gave function components state (useState), reducers (useReducer) and effects (useEffect). The Hooks RFC lists algebraic effects in Multicore OCaml among its sources, and Abramov’s 2019 essay “Algebraic Effects for the Rest of Us” called them a mental model the team uses, though JavaScript has no effect handlers.',
    ideas: ['tea'],
    magnitude: 2,
  },
  {
    id: 'swiftui',
    name: 'SwiftUI',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2019,
    people: 'Apple',
    epithet: 'Declarative UI for Apple platforms',
    blurb:
      'Apple introduced SwiftUI at WWDC 2019: views are lightweight values computed from state, and the framework works out what changed. It leaned on new Swift features, property wrappers like @State and function builders for nested views, and shipped alongside Combine, Apple’s Rx-style streams. Community architectures such as TCA bring Elm-style reducers to it.',
    ideas: ['frp'],
    magnitude: 2,
  },
  {
    id: 'excel-lambda',
    name: 'Excel LAMBDA',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2020,
    people:
      'Microsoft Excel team and Microsoft Research Cambridge (Andy Gordon, Simon Peyton Jones et al.)',
    epithet: 'The spreadsheet gets its own functions',
    blurb:
      'Announced in December 2020, LAMBDA lets Excel users define reusable functions out of ordinary formulas, name them and call them recursively, which Microsoft noted made the formula language Turing-complete. The researchers involved included Haskell designer Simon Peyton Jones, who had co-written an ICFP 2003 paper on user-defined functions for spreadsheets.',
    ideas: ['lambda'],
    magnitude: 2,
  },
  {
    id: 'bubbletea',
    name: 'Bubble Tea',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2020,
    people: 'Charm',
    epithet: 'The Elm Architecture in your terminal',
    blurb:
      'Charm’s Go framework for terminal apps (2020) says plainly that it is based on The Elm Architecture: a model, an Update method that returns the next model and a command, and a View that renders a string. It has become one of the most popular ways to build terminal interfaces in Go.',
    ideas: ['tea'],
    magnitude: 3,
  },
  {
    id: 'signals',
    name: 'Signals',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2021,
    people: 'Ryan Carniato (SolidJS); Preact and Angular teams',
    epithet: 'Spreadsheet cells for the DOM',
    blurb:
      'A signal is a value that knows who reads it: change it and only the computations and DOM nodes that depend on it update, with no virtual DOM diff. SolidJS 1.0 (2021) popularised the approach, which descends from Knockout’s observables (2010). Preact and Angular adopted signals, and a 2024 TC39 proposal aims to standardise them.',
    ideas: ['frp'],
    magnitude: 2,
  },
  {
    id: 'foldkit',
    name: 'Foldkit',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2025,
    people: 'Devin Jameson',
    epithet: 'The Elm Architecture on Effect: you are here',
    blurb:
      'Foldkit (2025) brings The Elm Architecture to TypeScript on top of Effect: a Schema-typed model, messages, a pure update that returns the next model plus commands, and a view. This galaxy is a Foldkit app: every click you make is a message, and the sky you are looking at is drawn from the model.',
    ideas: ['tea'],
    magnitude: 2,
  },

  // ARRAYS & DATA

  {
    id: 'apl',
    name: 'APL',
    kind: 'Language',
    constellation: 'Array',
    year: 1962,
    people: 'Kenneth Iverson, Adin Falkoff',
    epithet: 'Whole arrays, one symbol at a time',
    blurb:
      'Iverson’s 1962 book A Programming Language gave the notation its name; APL\\360 (1966) made it run, with a special typeball for its symbols. Operators like / (reduce) and ∘. (outer product) apply functions to whole arrays, so +/⍳100 sums the numbers 1 to 100. NumPy, R and MATLAB users think this way.',
    ideas: ['arrays', 'hof'],
    magnitude: 1,
  },
  {
    id: 'matlab',
    name: 'MATLAB',
    kind: 'Language',
    constellation: 'Array',
    year: 1984,
    people: 'Cleve Moler, Jack Little',
    epithet: 'The matrix as the only data type',
    blurb:
      'Moler wrote the first MATLAB in Fortran in the late 1970s so his students could use the LINPACK and EISPACK libraries without writing Fortran. In 1984 Jack Little, Moler and Steve Bangert founded MathWorks and released a commercial version rewritten in C. Solving a linear system as A\\b set the tone for numerical computing.',
    ideas: ['arrays'],
    magnitude: 3,
  },
  {
    id: 'j',
    name: 'J',
    kind: 'Language',
    constellation: 'Array',
    year: 1990,
    people: 'Kenneth Iverson, Roger Hui',
    epithet: 'APL in ASCII, with tacit trains',
    blurb:
      'Iverson and Hui released J in 1990: APL’s ideas spelled in ASCII, so no special keyboard. Its tacit style defines functions without naming their arguments; the fork (+/ % #) computes an average as sum divided by count. Forks and hooks are combinators in all but name.',
    ideas: ['arrays', 'pipelines'],
    magnitude: 3,
  },
  {
    id: 'k',
    name: 'K & q',
    kind: 'Language',
    constellation: 'Array',
    year: 1993,
    people: 'Arthur Whitney',
    epithet: 'Terse arrays for tick data',
    blurb:
      'Whitney, who had worked with Iverson and built A+ at Morgan Stanley, released K in 1993 through Kx Systems. Its interpreter is famously tiny. The kdb+ database (2003) and its query language q, a more readable layer over K, store and analyse time-series data at many trading firms.',
    ideas: ['arrays'],
    magnitude: 3,
  },
  {
    id: 'numpy',
    name: 'NumPy',
    kind: 'Tool',
    constellation: 'Array',
    year: 2006,
    people: 'Travis Oliphant; Jim Hugunin (Numeric)',
    epithet: 'APL’s arrays, inside Python',
    blurb:
      'Jim Hugunin’s Numeric (1995) gave Python fast n-dimensional arrays, and Oliphant merged it with its rival Numarray into NumPy in 2006. Broadcasting, which stretches arrays of different shapes to fit, and vectorised operations replaced loops. It is the base layer for pandas, SciPy and scikit-learn, and the model for PyTorch’s and JAX’s APIs.',
    ideas: ['arrays'],
    magnitude: 2,
  },
  {
    id: 'spark',
    name: 'Spark',
    kind: 'Tool',
    constellation: 'Array',
    year: 2010,
    people: 'Matei Zaharia, UC Berkeley AMPLab',
    epithet: 'Immutable datasets, transformed lazily',
    blurb:
      'Zaharia’s Spark (2010), written in Scala, generalised MapReduce with resilient distributed datasets: immutable collections you transform with map, filter and join. Transformations are lazy, so Spark sees the whole pipeline before running it, and a lost partition can be recomputed from its lineage rather than restored from a checkpoint.',
    ideas: ['hof', 'immutability', 'laziness'],
    magnitude: 2,
  },
  {
    id: 'julia',
    name: 'Julia',
    kind: 'Language',
    constellation: 'Array',
    year: 2012,
    people: 'Jeff Bezanson, Stefan Karpinski, Viral Shah, Alan Edelman',
    epithet: 'Multiple dispatch for scientists',
    blurb:
      'Julia was announced in 2012 with a post asking for Lisp’s macros, MATLAB’s notation and Python’s generality, without giving up speed. Every function is generic, and methods are chosen by the types of all the arguments, as in CLOS and Dylan. Its front end was written in femtolisp, a small Scheme by Bezanson, which julia --lisp still opens.',
    ideas: ['dispatch', 'arrays'],
    magnitude: 2,
  },
  {
    id: 'jax',
    name: 'JAX',
    kind: 'Tool',
    constellation: 'Array',
    year: 2018,
    people: 'Roy Frostig, Matthew Johnson, Chris Leary and Google',
    epithet: 'Transformations of pure functions',
    blurb:
      'JAX (2018) gives NumPy’s API composable function transformations: grad returns a function’s derivative, vmap vectorises it, jit compiles it with XLA. They work because the functions are pure, so even randomness is explicit, with splittable PRNG keys passed around as values. Much of Google DeepMind’s research runs on it.',
    ideas: ['purity', 'hof', 'arrays'],
    magnitude: 2,
  },

  // ACTORS & CONCURRENCY

  {
    id: 'erlang',
    name: 'Erlang',
    kind: 'Language',
    constellation: 'Actors',
    year: 1986,
    people: 'Joe Armstrong, Robert Virding, Mike Williams',
    epithet: 'Share nothing, let it crash',
    blurb:
      'Armstrong started Erlang at Ericsson in 1986, and the first interpreter was written in Prolog, which is why its syntax has full stops and capitalised variables. Processes are cheap and isolated, communicate only by messages, and a crash is reported to linked processes rather than hidden. Ericsson open-sourced it in 1998.',
    ideas: ['actors', 'supervision', 'fibers'],
    magnitude: 1,
  },
  {
    id: 'otp',
    name: 'OTP',
    kind: 'Tool',
    constellation: 'Actors',
    year: 1996,
    people: 'Ericsson',
    epithet: 'Supervision trees and behaviours',
    blurb:
      'The Open Telecom Platform (1996) packaged Erlang’s hard-won patterns as libraries. Behaviours like gen_server separate generic plumbing from your callbacks, and supervisors restart crashed workers according to a strategy such as one_for_one. An application becomes a tree of supervisors, so failure is contained and recovery is routine.',
    ideas: ['supervision'],
    magnitude: 2,
  },
  {
    id: 'akka',
    name: 'Akka',
    kind: 'Tool',
    constellation: 'Actors',
    year: 2009,
    people: 'Jonas Bonér',
    epithet: 'Erlang’s actors, on the JVM',
    blurb:
      'Bonér released Akka in 2009, bringing Erlang-style actors and supervision to Scala and Java; it is named after a mountain in Swedish Lapland. In 2022 its licence changed from Apache 2.0 to the Business Source License, and the community fork Apache Pekko carries on the open-source line.',
    ideas: ['actors', 'supervision'],
    magnitude: 2,
  },
  {
    id: 'elixir',
    name: 'Elixir',
    kind: 'Language',
    constellation: 'Actors',
    year: 2012,
    people: 'José Valim',
    epithet: 'The BEAM, with Ruby manners and macros',
    blurb:
      'Valim, then a member of the Rails core team, created Elixir in 2012 to bring better tooling, metaprogramming and a friendlier syntax to the Erlang VM. Its macros work on code represented as plain tuples, so much of the language is defined in Elixir itself. The |> pipe made data-first pipelines idiomatic, and Phoenix followed.',
    ideas: ['pipelines', 'homoiconicity'],
    magnitude: 1,
  },
  {
    id: 'gleam',
    name: 'Gleam',
    kind: 'Language',
    constellation: 'Actors',
    year: 2016,
    people: 'Louis Pilfold',
    epithet: 'ML-style types on the BEAM',
    blurb:
      'Pilfold started Gleam in 2016 to give the Erlang VM a statically typed language with inferred types, custom types and exhaustive case expressions, using Result values rather than exceptions for expected errors. Its compiler is written in Rust and can also target JavaScript. Version 1.0 arrived in March 2024.',
    ideas: ['inference', 'optionresult'],
    magnitude: 2,
  },

  // LOGIC & RELATIONS

  {
    id: 'planner',
    name: 'Planner',
    kind: 'Language',
    constellation: 'Logic',
    year: 1969,
    people: 'Carl Hewitt',
    epithet: 'Goals that summon the right procedure',
    blurb:
      'Hewitt’s Planner (1969) invoked procedures by pattern-matching on goals and assertions instead of calling them by name, backtracking automatically on failure. A subset, Micro-Planner, ran Terry Winograd’s SHRDLU blocks-world program. Arguments over Planner fed into Prolog, and Hewitt’s attempts to generalise it led to actors.',
    ideas: ['logic'],
    magnitude: 3,
  },
  {
    id: 'prolog',
    name: 'Prolog',
    kind: 'Language',
    constellation: 'Logic',
    year: 1972,
    people: 'Alain Colmerauer, Philippe Roussel, Robert Kowalski',
    epithet: 'Say what is true; let it search',
    blurb:
      'Colmerauer and Roussel built Prolog in Marseille in 1972 for natural-language processing, on Kowalski’s insight that Horn clauses can be read as procedures. You state facts and rules; unification and backtracking find the answers. Japan’s Fifth Generation project (1982) bet on logic programming, and Erlang’s first interpreter was written in Prolog.',
    ideas: ['logic'],
    magnitude: 1,
  },
  {
    id: 'sql',
    name: 'SQL',
    kind: 'Language',
    constellation: 'Logic',
    year: 1974,
    people: 'Donald Chamberlin, Raymond Boyce',
    epithet: 'Ask for what, not how',
    blurb:
      'Chamberlin and Boyce at IBM designed SEQUEL in 1974 as an English-like query language for Codd’s relational model; a trademark clash forced the shorter name. You declare the result you want and a query planner chooses the algorithm. It may be the most widely used declarative language there is.',
    ideas: ['logic', 'comprehensions'],
    magnitude: 2,
  },
  {
    id: 'datalog',
    name: 'Datalog',
    kind: 'Language',
    constellation: 'Logic',
    year: 1978,
    people: 'Hervé Gallaire, Jack Minker, Jean-Marie Nicolas et al.',
    epithet: 'Prolog that always terminates',
    blurb:
      'Datalog grew out of the 1977 Toulouse workshop on logic and databases, published as the book Logic and Data Bases in 1978; the name came later. It is Prolog without function symbols, so every query terminates and can be evaluated bottom-up. It returned through program analysis, where tools like Soufflé and CodeQL describe code as facts.',
    ideas: ['logic'],
    magnitude: 2,
  },
  {
    id: 'curry-lang',
    name: 'Curry',
    kind: 'Language',
    constellation: 'Logic',
    year: 1995,
    people: 'Michael Hanus, Herbert Kuchen, Juan José Moreno-Navarro',
    epithet: 'Haskell that can search',
    blurb:
      'Curry, designed from the mid-1990s by an international group led by Michael Hanus, adds logic variables and nondeterministic search to Haskell-like syntax. Functions can run with unknown arguments, which the system narrows down to solutions, combining lazy evaluation with Prolog-style search. Like Haskell, it is named after Haskell Curry.',
    ideas: ['logic', 'laziness'],
    magnitude: 3,
  },
  {
    id: 'datomic',
    name: 'Datomic',
    kind: 'Tool',
    constellation: 'Logic',
    year: 2012,
    people: 'Rich Hickey, Cognitect',
    epithet: 'A database of immutable facts',
    blurb:
      'Hickey’s Datomic (2012) stores data as an accumulating log of immutable facts, so you can query the database as it was at any moment. Queries are written in Datalog, expressed as Clojure data. Nubank, the Brazilian digital bank and a heavy user, bought its maker Cognitect in 2020.',
    ideas: ['immutability', 'logic'],
    magnitude: 3,
  },
  {
    id: 'codeql',
    name: 'CodeQL',
    kind: 'Tool',
    constellation: 'Logic',
    year: 2019,
    people: 'Semmle (Oege de Moor et al.), GitHub',
    epithet: 'Query code like a database',
    blurb:
      'CodeQL turns a codebase into a relational database of facts, then lets you query it in QL, an object-oriented Datalog dialect from Semmle, an Oxford spin-out. GitHub acquired Semmle in 2019, and GitHub code scanning uses CodeQL queries to find vulnerability patterns.',
    ideas: ['logic'],
    magnitude: 3,
  },

  // JAVASCRIPT’S FUNCTIONAL LIBRARIES

  {
    id: 'underscore',
    name: 'Underscore.js',
    kind: 'Tool',
    constellation: 'Array',
    year: 2009,
    people: 'Jeremy Ashkenas, DocumentCloud',
    epithet: 'The utility belt that taught JavaScript map',
    blurb:
      'Jeremy Ashkenas released Underscore at DocumentCloud in 2009: map, reduce, filter, compose, debounce and dozens more, without touching built-in prototypes. Its aliases collect, select, detect and inject are the Smalltalk and Ruby names for the same ideas. Ashkenas also created CoffeeScript and Backbone.',
    ideas: ['hof'],
    magnitude: 2,
  },
  {
    id: 'lodash',
    name: 'Lodash',
    kind: 'Tool',
    constellation: 'Array',
    year: 2012,
    people: 'John-David Dalton',
    epithet: 'Underscore, forked for consistency and speed',
    blurb:
      'John-David Dalton forked Underscore in 2012 as a drop-in replacement that behaved the same in every browser and ran faster, and Lodash soon outgrew its parent. Version 4 (2016) added lodash/fp, auto-curried and data-last, in the style Ramda had popularised. For years it was among the most depended-upon packages on npm.',
    ideas: ['hof', 'pipelines'],
    magnitude: 2,
  },
  {
    id: 'ramda',
    name: 'Ramda',
    kind: 'Tool',
    constellation: 'Array',
    year: 2013,
    people: 'Scott Sauyet, Michael Hurley',
    epithet: 'Curried, data-last, and never mutating',
    blurb:
      'Sauyet and Hurley built Ramda (2013) for composition: every function is curried and takes its data last, so R.pipe(R.filter(isEven), R.map(square)) is itself a function waiting for a list, and nothing mutates its input. Brian Lonsdorf’s 2013 talk “Hey Underscore, You’re Doing It Wrong!” had argued that Underscore’s data-first argument order gets in the way of currying and composition.',
    ideas: ['pipelines', 'purity', 'immutability'],
    magnitude: 2,
  },
  {
    id: 'fantasy-land',
    name: 'Fantasy Land',
    kind: 'Theory',
    constellation: 'Effects',
    year: 2013,
    people: 'Brian McKenna and contributors',
    epithet: 'Type class laws, written down for JavaScript',
    blurb:
      'Fantasy Land (2013), started by Brian McKenna, is a specification: if your JavaScript type has methods like map and chain that obey the stated laws, it is a Functor or a Monad, and any compliant library can work with it. The name answers a 2013 Promises/A+ thread in which making then a monad was dismissed as typed-language “fantasy land”.',
    ideas: ['monads', 'typeclasses'],
    magnitude: 2,
  },
  {
    id: 'folktale',
    name: 'Folktale',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2013,
    people: 'Quildreen Motta',
    epithet: 'Maybe, Either and Task for JavaScript',
    blurb:
      'Quildreen Motta’s Folktale (from 2013) gave JavaScript a standard library of algebraic data types: Maybe, Either, Validation, and Task, a lazy alternative to Promise that does nothing until it is run. Its types implemented Fantasy Land, so they composed with other compliant libraries.',
    ideas: ['optionresult', 'monads'],
    magnitude: 3,
  },
  {
    id: 'sanctuary',
    name: 'Sanctuary',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2015,
    people: 'David Chambers',
    epithet: 'A refuge from unsafe JavaScript',
    blurb:
      'David Chambers’s Sanctuary (2015) is a Ramda-like library, inspired by Haskell and PureScript, whose functions never return null or throw: they return Maybe or Either instead. It checks the types of arguments at run time and reports mistakes using Haskell-style type signatures.',
    ideas: ['optionresult', 'purity'],
    magnitude: 3,
  },
  {
    id: 'fluture',
    name: 'Fluture',
    kind: 'Tool',
    constellation: 'Effects',
    year: 2016,
    people: 'Aldwin Vlasblom',
    epithet: 'A Promise that waits to be asked',
    blurb:
      'Aldwin Vlasblom’s Fluture (2016) is a Future that fixes what functional programmers disliked about Promise: it is lazy, so building one runs nothing until you fork it; it can be cancelled; and it is a lawful Fantasy Land monad that never flattens nested values behind your back the way then does.',
    ideas: ['monads', 'laziness'],
    magnitude: 3,
  },
  {
    id: 'mori',
    name: 'Mori',
    kind: 'Tool',
    constellation: 'Lisp',
    year: 2012,
    people: 'David Nolen',
    epithet: 'ClojureScript’s collections, for plain JavaScript',
    blurb:
      'David Nolen packaged ClojureScript’s persistent vectors, maps and sets as Mori (2012), usable from plain JavaScript with no Clojure in sight. Nolen, a ClojureScript lead, also wrote Om, which paired React with immutable data and showed that unchanged data can mean a skipped re-render.',
    ideas: ['immutability'],
    magnitude: 3,
  },
  {
    id: 'bacon',
    name: 'Bacon.js',
    kind: 'Tool',
    constellation: 'Reactive',
    year: 2012,
    people: 'Juha Paananen',
    epithet: 'Event streams instead of callback spaghetti',
    blurb:
      'Juha Paananen’s Bacon.js (2012) brought functional reactive programming to everyday JavaScript, distinguishing EventStreams, discrete occurrences, from Properties, which always have a current value. Instead of nesting callbacks you could map, filter, merge and combine streams of clicks and responses.',
    ideas: ['frp'],
    magnitude: 3,
  },
  {
    id: 'mostly-adequate',
    name: 'Mostly Adequate Guide',
    kind: 'Theory',
    constellation: 'Effects',
    year: 2015,
    people: 'Brian Lonsdorf',
    epithet: 'Functors and monads, explained by Professor Frisby',
    blurb:
      'Brian Lonsdorf’s free online book, Professor Frisby’s Mostly Adequate Guide to Functional Programming, taught currying, composition, functors and monads in plain JavaScript, with plenty of jokes. For many web developers it was the first time Maybe, Either, IO and Task made sense, before those types reached the mainstream through fp-ts and Effect.',
    ideas: ['monads', 'purity'],
    magnitude: 3,
  },
]
